/*
 * p了个s · 英了个语 词库释义 · 5 字母 (src/game2/meanings5.ts)
 * ===========================================================
 * 5 字母词释义(词性 + 中文, 多词性/多义项全部列出)。
 * 生成器只从「有释义的词」中取词, 保证对局内每个词都能在结算页逐条查看。
 */
export const YLGY_MEANINGS_5: Record<string, { pos: string; zh: string }[]> = {
    "about": [{ pos: "prep.", zh: "关于;大约;到处" }, { pos: "adv.", zh: "大约;附近" }],
    "above": [{ pos: "prep.", zh: "在…上方;超过;高于" }, { pos: "adv.", zh: "在上面;以上" }],
    "actor": [{ pos: "n.", zh: "演员;男演员" }],
    "adapt": [{ pos: "v.", zh: "适应;改编;使适合" }],
    "admit": [{ pos: "v.", zh: "承认;准许进入;容纳" }],
    "adopt": [{ pos: "v.", zh: "收养;采用;采纳" }],
    "adult": [{ pos: "n.", zh: "成年人;成人" }, { pos: "adj.", zh: "成年的;成熟的" }],
    "after": [{ pos: "prep.", zh: "在…之后;依照" }, { pos: "conj.", zh: "在…以后" }, { pos: "adv.", zh: "后来;以后" }],
    "again": [{ pos: "adv.", zh: "再一次;又;再" }],
    "agent": [{ pos: "n.", zh: "代理人;代理商;特工;经纪人" }],
    "agree": [{ pos: "v.", zh: "同意;赞成;一致;适合" }],
    "ahead": [{ pos: "adv.", zh: "在前面;向前;提前" }],
    "allow": [{ pos: "v.", zh: "允许;准许;同意;给予" }],
    "alone": [{ pos: "adj.", zh: "单独的;孤独的" }, { pos: "adv.", zh: "独自;仅仅" }],
    "along": [{ pos: "prep.", zh: "沿着;顺着" }, { pos: "adv.", zh: "向前;一起" }],
    "aloud": [{ pos: "adv.", zh: "大声地;出声地" }],
    "alter": [{ pos: "v.", zh: "改变;更改;修改" }],
    "among": [{ pos: "prep.", zh: "在…之中;在…中间" }],
    "anger": [{ pos: "n.", zh: "愤怒;生气" }, { pos: "v.", zh: "激怒;使生气" }],
    "angle": [{ pos: "n.", zh: "角;角度;观点" }],
    "angry": [{ pos: "adj.", zh: "生气的;愤怒的" }],
    "apart": [{ pos: "adv.", zh: "分开;相距;分离" }],
    "apple": [{ pos: "n.", zh: "苹果" }],
    "apply": [{ pos: "v.", zh: "申请;应用;适用;涂敷" }],
    "argue": [{ pos: "v.", zh: "争论;辩论;主张" }],
    "arise": [{ pos: "v.", zh: "出现;产生;上升" }],
    "aside": [{ pos: "adv.", zh: "在旁边;到一边" }],
    "avoid": [{ pos: "v.", zh: "避免;避开;预防" }],
    "awake": [{ pos: "adj.", zh: "醒着的;清醒的" }, { pos: "v.", zh: "唤醒;醒来" }],
    "award": [{ pos: "n.", zh: "奖;奖品;奖金" }, { pos: "v.", zh: "授予;颁发" }],
    "aware": [{ pos: "adj.", zh: "意识到的;知道的" }],
    "awful": [{ pos: "adj.", zh: "糟糕的;可怕的;极度的" }],
    "baker": [{ pos: "n.", zh: "面包师;烘烤师傅" }],
    "basic": [{ pos: "adj.", zh: "基本的;基础的" }],
    "basis": [{ pos: "n.", zh: "基础;根据;基准" }],
    "beach": [{ pos: "n.", zh: "海滩;海滨" }],
    "beard": [{ pos: "n.", zh: "胡须;胡子" }],
    "beast": [{ pos: "n.", zh: "野兽;牲畜;凶残的人" }],
    "begin": [{ pos: "v.", zh: "开始;着手" }],
    "being": [{ pos: "n.", zh: "存在;生物;人" }],
    "below": [{ pos: "prep.", zh: "在…下面;低于" }, { pos: "adv.", zh: "在下面" }],
    "bench": [{ pos: "n.", zh: "长凳;工作台;替补席" }],
    "birth": [{ pos: "n.", zh: "出生;诞生;起源" }],
    "black": [{ pos: "adj.", zh: "黑色的;黑暗的" }, { pos: "n.", zh: "黑色" }],
    "blame": [{ pos: "v.", zh: "责备;归咎于" }, { pos: "n.", zh: "责备;责任" }],
    "blank": [{ pos: "adj.", zh: "空白的;茫然的" }, { pos: "n.", zh: "空白;空格" }],
    "blast": [{ pos: "n.", zh: "爆炸;一阵强风" }, { pos: "v.", zh: "炸毁;猛攻" }],
    "bleed": [{ pos: "v.", zh: "流血;出血;放血" }],
    "bless": [{ pos: "v.", zh: "祝福;保佑;赞美" }],
    "blind": [{ pos: "adj.", zh: "瞎的;失明的;盲目的" }, { pos: "v.", zh: "使失明;蒙蔽" }],
    "block": [{ pos: "n.", zh: "街区;块;障碍物;积木" }, { pos: "v.", zh: "阻塞;阻挡;封锁" }],
    "blood": [{ pos: "n.", zh: "血;血液;血统" }],
    "board": [{ pos: "n.", zh: "木板;板;委员会;董事会;膳食" }, { pos: "v.", zh: "上船/车/飞机;登机" }],
    "brave": [{ pos: "adj.", zh: "勇敢的;无畏的" }, { pos: "v.", zh: "勇敢面对" }],
    "bread": [{ pos: "n.", zh: "面包;食物" }],
    "break": [{ pos: "v.", zh: "打破;折断;违反;休息" }, { pos: "n.", zh: "休息;破裂;间歇" }],
    "brick": [{ pos: "n.", zh: "砖;砖块" }],
    "bride": [{ pos: "n.", zh: "新娘" }],
    "brief": [{ pos: "adj.", zh: "简短的;短暂的" }, { pos: "n.", zh: "摘要;简报" }, { pos: "v.", zh: "简要介绍" }],
    "bring": [{ pos: "v.", zh: "带来;拿来;引起;导致" }],
    "broad": [{ pos: "adj.", zh: "宽阔的;广泛的;粗略的" }],
    "brown": [{ pos: "adj.", zh: "棕色的;褐色的" }, { pos: "n.", zh: "棕色" }],
    "brush": [{ pos: "n.", zh: "刷子;画笔;刷" }, { pos: "v.", zh: "刷;擦;轻触" }],
    "build": [{ pos: "v.", zh: "建造;建立;发展" }, { pos: "n.", zh: "体格;身材" }],
    "burst": [{ pos: "v.", zh: "爆裂;突然发生;冲" }, { pos: "n.", zh: "爆发;破裂" }],
    "cabin": [{ pos: "n.", zh: "小屋;船舱;机舱" }],
    "candy": [{ pos: "n.", zh: "糖果" }],
    "carry": [{ pos: "v.", zh: "携带;搬运;运送;支持" }],
    "catch": [{ pos: "v.", zh: "抓住;赶上;感染;理解" }, { pos: "n.", zh: "捕获;接球" }],
    "cause": [{ pos: "n.", zh: "原因;理由;事业" }, { pos: "v.", zh: "引起;导致" }],
    "cease": [{ pos: "v.", zh: "停止;终止;结束" }],
    "chain": [{ pos: "n.", zh: "链;链条;连锁店;一连串" }],
    "chair": [{ pos: "n.", zh: "椅子;主席;教授职位" }, { pos: "v.", zh: "主持" }],
    "chalk": [{ pos: "n.", zh: "粉笔;白垩" }],
    "charm": [{ pos: "n.", zh: "魅力;吸引力;符咒" }, { pos: "v.", zh: "迷住;吸引" }],
    "chart": [{ pos: "n.", zh: "图表;海图;排行榜" }, { pos: "v.", zh: "绘制图表;记录" }],
    "chase": [{ pos: "v.", zh: "追逐;追赶;追求" }, { pos: "n.", zh: "追逐;追赶" }],
    "cheap": [{ pos: "adj.", zh: "便宜的;廉价的;低劣的" }],
    "cheat": [{ pos: "v.", zh: "欺骗;作弊;骗取" }, { pos: "n.", zh: "骗子;欺骗" }],
    "check": [{ pos: "v.", zh: "检查;核对;阻止;开支票" }, { pos: "n.", zh: "检查;支票;账单" }],
    "cheek": [{ pos: "n.", zh: "脸颊;面颊;厚脸皮" }],
    "cheer": [{ pos: "v.", zh: "欢呼;加油;使高兴" }, { pos: "n.", zh: "欢呼;愉快" }],
    "chess": [{ pos: "n.", zh: "国际象棋" }],
    "chest": [{ pos: "n.", zh: "胸膛;胸部;箱子;柜子" }],
    "chief": [{ pos: "n.", zh: "首领;酋长;主任" }, { pos: "adj.", zh: "主要的;首要的" }],
    "child": [{ pos: "n.", zh: "孩子;儿童;子女" }],
    "china": [{ pos: "n.", zh: "瓷器;瓷(China=中国)" }],
    "claim": [{ pos: "v.", zh: "声称;要求;索取;认领" }, { pos: "n.", zh: "声明;索赔;要求" }],
    "clash": [{ pos: "v.", zh: "冲突;抵触;碰撞" }, { pos: "n.", zh: "冲突;碰撞声" }],
    "class": [{ pos: "n.", zh: "班级;课;阶级;等级;种类" }],
    "clean": [{ pos: "adj.", zh: "干净的;清洁的;纯洁的" }, { pos: "v.", zh: "打扫;清洁" }],
    "clear": [{ pos: "adj.", zh: "清楚的;清晰的;晴朗的;透明的" }, { pos: "v.", zh: "清除;清理;变晴" }],
    "clerk": [{ pos: "n.", zh: "职员;店员;办事员" }],
    "climb": [{ pos: "v.", zh: "爬;攀登;上升" }, { pos: "n.", zh: "攀登;爬升" }],
    "clock": [{ pos: "n.", zh: "时钟;钟表" }],
    "close": [{ pos: "v.", zh: "关闭;结束;接近" }, { pos: "adj.", zh: "近的;亲密的;关闭的" }, { pos: "adv.", zh: "接近地" }],
    "cloth": [{ pos: "n.", zh: "布;布料;织物" }],
    "cloud": [{ pos: "n.", zh: "云;云朵;阴影" }],
    "coach": [{ pos: "n.", zh: "教练;长途客车;四轮马车" }, { pos: "v.", zh: "训练;指导" }],
    "coast": [{ pos: "n.", zh: "海岸;海滨" }],
    "color": [{ pos: "n.", zh: "颜色;色彩;颜料" }, { pos: "v.", zh: "着色;染色" }],
    "count": [{ pos: "v.", zh: "数;计数;计算;认为;重要" }, { pos: "n.", zh: "计数;总数" }],
    "court": [{ pos: "n.", zh: "法院;法庭;球场;宫廷;庭院" }],
    "cover": [{ pos: "v.", zh: "覆盖;遮盖;包括;报道;支付" }, { pos: "n.", zh: "封面;盖子;掩护;保险" }],
    "crack": [{ pos: "n.", zh: "裂缝;裂纹;破解" }, { pos: "v.", zh: "破裂;裂开;破解" }],
    "craft": [{ pos: "n.", zh: "手艺;工艺;船;飞机" }],
    "crash": [{ pos: "v.", zh: "碰撞;坠毁;崩溃" }, { pos: "n.", zh: "碰撞;坠毁;崩溃" }],
    "crazy": [{ pos: "adj.", zh: "疯狂的;狂热的;荒唐的" }],
    "cream": [{ pos: "n.", zh: "奶油;乳脂;护肤霜;精华" }],
    "crime": [{ pos: "n.", zh: "罪行;犯罪;罪恶" }],
    "cross": [{ pos: "v.", zh: "穿过;横过;交叉;反对" }, { pos: "n.", zh: "十字;交叉;磨难" }, { pos: "adj.", zh: "生气的;相反的" }],
    "crowd": [{ pos: "n.", zh: "人群;群众;一群" }, { pos: "v.", zh: "聚集;挤满" }],
    "crown": [{ pos: "n.", zh: "王冠;皇冠;顶部;牙冠" }],
    "cruel": [{ pos: "adj.", zh: "残忍的;残酷的;无情的" }],
    "cycle": [{ pos: "n.", zh: "循环;周期;自行车" }, { pos: "v.", zh: "骑自行车;循环" }],
    "daily": [{ pos: "adj.", zh: "每日的;日常的" }, { pos: "adv.", zh: "每日;天天" }, { pos: "n.", zh: "日报" }],
    "dance": [{ pos: "v.", zh: "跳舞;舞蹈" }, { pos: "n.", zh: "舞蹈;舞会" }],
    "death": [{ pos: "n.", zh: "死亡;去世;终止" }],
    "delay": [{ pos: "v.", zh: "推迟;延误;耽搁" }, { pos: "n.", zh: "延迟;延误" }],
    "depth": [{ pos: "n.", zh: "深度;深处;深刻" }],
    "diary": [{ pos: "n.", zh: "日记;日记本" }],
    "dirty": [{ pos: "adj.", zh: "脏的;肮脏的;下流的" }],
    "doubt": [{ pos: "n.", zh: "怀疑;疑问;不确定" }, { pos: "v.", zh: "怀疑;不相信" }],
    "dozen": [{ pos: "n.", zh: "一打;十二个" }],
    "draft": [{ pos: "n.", zh: "草稿;草案;汇票;征兵" }, { pos: "v.", zh: "起草;拟稿" }],
    "drama": [{ pos: "n.", zh: "戏剧;剧本;戏剧性事件" }],
    "dream": [{ pos: "n.", zh: "梦;梦想;愿望" }, { pos: "v.", zh: "做梦;梦想;向往" }],
    "dress": [{ pos: "n.", zh: "连衣裙;服装;礼服" }, { pos: "v.", zh: "穿衣;给…穿衣;打扮" }],
    "drink": [{ pos: "v.", zh: "喝;饮酒" }, { pos: "n.", zh: "饮料;酒" }],
    "drive": [{ pos: "v.", zh: "驾驶;开车;驱动;迫使" }, { pos: "n.", zh: "驾车旅行;车道;干劲" }],
    "eager": [{ pos: "adj.", zh: "渴望的;热切的;急切的" }],
    "eagle": [{ pos: "n.", zh: "鹰;雕" }],
    "early": [{ pos: "adj.", zh: "早的;早期的;提前的" }, { pos: "adv.", zh: "早;提早;在初期" }],
    "earth": [{ pos: "n.", zh: "地球;陆地;泥土;大地" }],
    "eight": [{ pos: "num.", zh: "八;八个" }],
    "elder": [{ pos: "adj.", zh: "年长的;资格老的" }, { pos: "n.", zh: "长者;前辈" }],
    "elect": [{ pos: "v.", zh: "选举;推选;选择" }],
    "empty": [{ pos: "adj.", zh: "空的;空虚的;空洞的" }, { pos: "v.", zh: "倒空;变空" }],
    "enemy": [{ pos: "n.", zh: "敌人;仇人;敌国;敌军" }],
    "enjoy": [{ pos: "v.", zh: "享受;欣赏;喜爱;过得愉快" }],
    "enter": [{ pos: "v.", zh: "进入;进来;参加;输入;登记" }],
    "equal": [{ pos: "adj.", zh: "相等的;平等的;胜任的" }, { pos: "n.", zh: "相等的人或物" }, { pos: "v.", zh: "等于;比得上" }],
    "error": [{ pos: "n.", zh: "错误;误差;谬误" }],
    "essay": [{ pos: "n.", zh: "文章;短文;散文;论文" }],
    "event": [{ pos: "n.", zh: "事件;大事;活动;比赛项目" }],
    "every": [{ pos: "adj.", zh: "每个;每一;所有的" }],
    "exact": [{ pos: "adj.", zh: "精确的;准确的;严谨的" }],
    "exist": [{ pos: "v.", zh: "存在;生存;生活" }],
    "extra": [{ pos: "adj.", zh: "额外的;附加的" }, { pos: "adv.", zh: "额外;特别" }, { pos: "n.", zh: "额外的事物" }],
    "faint": [{ pos: "adj.", zh: "微弱的;模糊的;虚弱的" }, { pos: "v.", zh: "昏厥;晕倒" }],
    "faith": [{ pos: "n.", zh: "信念;信仰;信任;忠诚" }],
    "false": [{ pos: "adj.", zh: "错误的;假的;伪造的;不忠实的" }],
    "fancy": [{ pos: "adj.", zh: "花哨的;昂贵的;高档的" }, { pos: "v.", zh: "想要;幻想;喜爱" }, { pos: "n.", zh: "幻想;爱好" }],
    "fatal": [{ pos: "adj.", zh: "致命的;灾难性的;决定性的" }],
    "fault": [{ pos: "n.", zh: "过错;缺点;故障;断层" }],
    "favor": [{ pos: "n.", zh: "恩惠;帮助;赞同;偏爱" }, { pos: "v.", zh: "赞成;偏爱;有利于" }],
    "fence": [{ pos: "n.", zh: "栅栏;篱笆;围墙" }],
    "fetch": [{ pos: "v.", zh: "取来;拿来;接来;售得" }],
    "fever": [{ pos: "n.", zh: "发烧;发热;狂热" }],
    "field": [{ pos: "n.", zh: "田地;田野;领域;场地;现场" }],
    "fight": [{ pos: "v.", zh: "打架;战斗;斗争;对抗" }, { pos: "n.", zh: "战斗;打架;争论" }],
    "final": [{ pos: "adj.", zh: "最后的;最终的;决定性的" }, { pos: "n.", zh: "决赛;期终考试" }],
    "first": [{ pos: "num.", zh: "第一" }, { pos: "adj.", zh: "第一的;最初的;首要的" }, { pos: "adv.", zh: "首先;最初" }],
    "fixed": [{ pos: "adj.", zh: "固定的;不变的;坚定的" }],
    "flash": [{ pos: "n.", zh: "闪光;闪现;闪光灯;瞬间" }, { pos: "v.", zh: "闪光;闪现;飞速发送" }],
    "flesh": [{ pos: "n.", zh: "肉;果肉;肉体" }],
    "float": [{ pos: "v.", zh: "漂浮;浮动;飘动" }, { pos: "n.", zh: "浮标;漂浮物" }],
    "flood": [{ pos: "n.", zh: "洪水;水灾;大量" }, { pos: "v.", zh: "淹没;泛滥;涌入" }],
    "floor": [{ pos: "n.", zh: "地板;地面;楼层;底部" }],
    "flour": [{ pos: "n.", zh: "面粉;粉" }],
    "focus": [{ pos: "v.", zh: "集中;聚焦;关注" }, { pos: "n.", zh: "焦点;中心;重点" }],
    "force": [{ pos: "n.", zh: "力量;武力;军队;影响力" }, { pos: "v.", zh: "强迫;迫使;用力推动" }],
    "forth": [{ pos: "adv.", zh: "向前;向外;以后" }],
    "forty": [{ pos: "num.", zh: "四十" }],
    "found": [{ pos: "v.", zh: "建立;创办;创立" }],
    "frame": [{ pos: "n.", zh: "框架;边框;结构;体格" }, { pos: "v.", zh: "给…装框;制定;陷害" }],
    "fresh": [{ pos: "adj.", zh: "新鲜的;清新的;新的;淡水的" }],
    "front": [{ pos: "n.", zh: "前面;正面;前线" }, { pos: "adj.", zh: "前面的;正面的" }],
    "fruit": [{ pos: "n.", zh: "水果;果实;成果" }],
    "ghost": [{ pos: "n.", zh: "鬼;幽灵;灵魂" }],
    "giant": [{ pos: "n.", zh: "巨人;巨物;巨头" }, { pos: "adj.", zh: "巨大的" }],
    "given": [{ pos: "adj.", zh: "给定的;特定的;假设的" }],
    "glass": [{ pos: "n.", zh: "玻璃;玻璃杯;眼镜;玻璃器皿" }],
    "globe": [{ pos: "n.", zh: "地球;地球仪;球体;全球" }],
    "glory": [{ pos: "n.", zh: "光荣;荣誉;辉煌;壮观" }],
    "goods": [{ pos: "n.", zh: "商品;货物;物品" }],
    "goose": [{ pos: "n.", zh: "鹅;鹅肉" }],
    "grace": [{ pos: "n.", zh: "优雅;恩惠;宽限;祷告" }],
    "grade": [{ pos: "n.", zh: "年级;等级;成绩;评分" }, { pos: "v.", zh: "评分;分级" }],
    "grain": [{ pos: "n.", zh: "谷物;粮食;颗粒;纹理" }],
    "grand": [{ pos: "adj.", zh: "宏伟的;壮丽的;重大的;豪华的" }],
    "grant": [{ pos: "v.", zh: "授予;准予;承认" }, { pos: "n.", zh: "拨款;补助金;授予" }],
    "grass": [{ pos: "n.", zh: "草;草地;草坪" }],
    "grave": [{ pos: "n.", zh: "坟墓;墓地" }, { pos: "adj.", zh: "严重的;严肃的;重大的" }],
    "great": [{ pos: "adj.", zh: "伟大的;巨大的;极好的;重要的" }],
    "green": [{ pos: "adj.", zh: "绿色的;青的;环保的;幼稚的" }, { pos: "n.", zh: "绿色;草地" }],
    "greet": [{ pos: "v.", zh: "问候;迎接;打招呼" }],
    "guard": [{ pos: "n.", zh: "警卫;卫兵;守卫;防护" }, { pos: "v.", zh: "保卫;守卫;防范" }],
    "guess": [{ pos: "v.", zh: "猜测;猜想;推测" }, { pos: "n.", zh: "猜测;猜想" }],
    "guest": [{ pos: "n.", zh: "客人;宾客;旅客" }],
    "guide": [{ pos: "n.", zh: "向导;导游;指南;指导" }, { pos: "v.", zh: "指导;引导;带领" }],
    "guilt": [{ pos: "n.", zh: "内疚;罪行;罪责" }],
    "habit": [{ pos: "n.", zh: "习惯;习性;癖好" }],
    "happy": [{ pos: "adj.", zh: "快乐的;幸福的;高兴的" }],
    "harsh": [{ pos: "adj.", zh: "严厉的;严酷的;刺耳的;粗糙的" }],
    "haste": [{ pos: "n.", zh: "匆忙;急忙;仓促" }],
    "heart": [{ pos: "n.", zh: "心脏;心;内心;中心;爱心" }],
    "heavy": [{ pos: "adj.", zh: "重的;沉重的;大量的;剧烈的" }],
    "hobby": [{ pos: "n.", zh: "业余爱好;嗜好" }],
    "honey": [{ pos: "n.", zh: "蜂蜜;亲爱的(昵称)" }],
    "honor": [{ pos: "n.", zh: "荣誉;光荣;尊敬;信誉" }, { pos: "v.", zh: "尊敬;给…荣誉;兑现" }],
    "horse": [{ pos: "n.", zh: "马" }],
    "hotel": [{ pos: "n.", zh: "旅馆;酒店;宾馆" }],
    "house": [{ pos: "n.", zh: "房子;房屋;住宅;家庭" }, { pos: "v.", zh: "给…提供住房;收藏" }],
    "human": [{ pos: "n.", zh: "人;人类" }, { pos: "adj.", zh: "人的;人类的;有人情味的" }],
    "humor": [{ pos: "n.", zh: "幽默;幽默感;心情" }],
    "hurry": [{ pos: "v.", zh: "匆忙;赶快;催促" }, { pos: "n.", zh: "匆忙;急忙" }],
    "ideal": [{ pos: "adj.", zh: "理想的;完美的;想象的" }, { pos: "n.", zh: "理想;典范;目标" }],
    "image": [{ pos: "n.", zh: "图像;形象;印象;意象" }],
    "imply": [{ pos: "v.", zh: "暗示;意味着;含有…意思" }],
    "index": [{ pos: "n.", zh: "索引;指数;标志" }],
    "inner": [{ pos: "adj.", zh: "内部的;内心的;里面的" }],
    "issue": [{ pos: "n.", zh: "问题;议题;发行;期号" }, { pos: "v.", zh: "发布;发行;发表" }],
    "judge": [{ pos: "n.", zh: "法官;裁判;鉴定人" }, { pos: "v.", zh: "判断;评判;审判" }],
    "juice": [{ pos: "n.", zh: "果汁;汁液" }],
    "knife": [{ pos: "n.", zh: "刀;小刀;餐刀" }],
    "knock": [{ pos: "v.", zh: "敲;打;碰撞;批评" }, { pos: "n.", zh: "敲;敲门声;打击" }],
    "labor": [{ pos: "n.", zh: "劳动;工作;劳工;分娩" }],
    "large": [{ pos: "adj.", zh: "大的;巨大的;大量的" }],
    "laser": [{ pos: "n.", zh: "激光;激光器" }],
    "later": [{ pos: "adv.", zh: "后来;以后;较晚地" }, { pos: "adj.", zh: "较晚的;后来的" }],
    "laugh": [{ pos: "v.", zh: "笑;发笑;嘲笑" }, { pos: "n.", zh: "笑;笑声" }],
    "layer": [{ pos: "n.", zh: "层;层次;阶层" }],
    "learn": [{ pos: "v.", zh: "学习;学会;得知;记住" }],
    "least": [{ pos: "adj.", zh: "最少的;最小的" }, { pos: "adv.", zh: "最少;最小" }],
    "leave": [{ pos: "v.", zh: "离开;出发;留下;遗忘;请假" }, { pos: "n.", zh: "假期;许可" }],
    "legal": [{ pos: "adj.", zh: "合法的;法律的;法定的" }],
    "lemon": [{ pos: "n.", zh: "柠檬;柠檬色" }],
    "level": [{ pos: "n.", zh: "水平;等级;层次;标准" }, { pos: "adj.", zh: "平的;水平的;同等的" }],
    "light": [{ pos: "n.", zh: "光;光线;灯;轻" }, { pos: "adj.", zh: "轻的;明亮的;浅色的;清淡的" }, { pos: "v.", zh: "点燃;照亮;使变亮" }],
    "limit": [{ pos: "n.", zh: "限制;限度;极限;界限" }, { pos: "v.", zh: "限制;限定" }],
    "liver": [{ pos: "n.", zh: "肝脏;肝" }],
    "lobby": [{ pos: "n.", zh: "大厅;门厅;游说团体" }, { pos: "v.", zh: "游说" }],
    "local": [{ pos: "adj.", zh: "当地的;地方的;局部的" }, { pos: "n.", zh: "本地人;当地居民" }],
    "logic": [{ pos: "n.", zh: "逻辑;逻辑学;推理" }],
    "loose": [{ pos: "adj.", zh: "松的;松散的;宽松的;不精确的" }],
    "lover": [{ pos: "n.", zh: "爱好者;情人;恋人" }],
    "lower": [{ pos: "adj.", zh: "较低的;下部的;下级的" }, { pos: "v.", zh: "降低;放下;减弱" }],
    "loyal": [{ pos: "adj.", zh: "忠诚的;忠实的" }],
    "lucky": [{ pos: "adj.", zh: "幸运的;侥幸的;吉祥的" }],
    "lunch": [{ pos: "n.", zh: "午餐;午饭" }],
    "magic": [{ pos: "n.", zh: "魔法;魔术;魔力;魅力" }, { pos: "adj.", zh: "有魔力的;魔术的" }],
    "major": [{ pos: "adj.", zh: "主要的;重要的;大的;主修的" }, { pos: "n.", zh: "专业;主修科目;少校" }],
    "march": [{ pos: "v.", zh: "行进;行军;游行;前进" }, { pos: "n.", zh: "三月;行进;游行" }],
    "match": [{ pos: "n.", zh: "比赛;火柴;匹配;对手" }, { pos: "v.", zh: "匹配;相配;比得上" }],
    "mayor": [{ pos: "n.", zh: "市长;镇长" }],
    "meant": [{ pos: "v.", zh: "mean 的过去式(意思是;打算)" }],
    "medal": [{ pos: "n.", zh: "奖章;勋章;奖牌" }],
    "media": [{ pos: "n.", zh: "媒体;媒介;大众传播工具" }],
    "mercy": [{ pos: "n.", zh: "仁慈;宽恕;怜悯" }],
    "merit": [{ pos: "n.", zh: "优点;价值;功绩" }, { pos: "v.", zh: "值得;应得" }],
    "merry": [{ pos: "adj.", zh: "快乐的;愉快的;兴高采烈的" }],
    "metal": [{ pos: "n.", zh: "金属;金属制品" }],
    "meter": [{ pos: "n.", zh: "米;公尺;仪表;计量器" }],
    "might": [{ pos: "aux.", zh: "可能;也许;可以" }, { pos: "n.", zh: "力量;威力;权势" }],
    "minor": [{ pos: "adj.", zh: "较小的;次要的;未成年的" }, { pos: "n.", zh: "未成年人;辅修科目" }],
    "minus": [{ pos: "prep.", zh: "减去;零下;没有" }, { pos: "adj.", zh: "负的;减号的" }],
    "mixed": [{ pos: "adj.", zh: "混合的;混杂的;复杂的" }],
    "model": [{ pos: "n.", zh: "模型;模特;模式;榜样;型号" }, { pos: "v.", zh: "建模;当模特" }],
    "money": [{ pos: "n.", zh: "钱;货币;财富" }],
    "month": [{ pos: "n.", zh: "月;月份" }],
    "moral": [{ pos: "adj.", zh: "道德的;道义上的;品行端正的" }, { pos: "n.", zh: "寓意;道德;教训" }],
    "motor": [{ pos: "n.", zh: "发动机;马达;电动机" }],
    "mount": [{ pos: "v.", zh: "登上;爬上;安装;增加" }, { pos: "n.", zh: "山;山峰(Mount=…山)" }],
    "mouse": [{ pos: "n.", zh: "老鼠;鼠标" }],
    "mouth": [{ pos: "n.", zh: "嘴;口;入口" }],
    "movie": [{ pos: "n.", zh: "电影;影片" }],
    "music": [{ pos: "n.", zh: "音乐;乐曲;乐谱" }],
    "naked": [{ pos: "adj.", zh: "裸体的;赤裸的;无遮盖的" }],
    "nasty": [{ pos: "adj.", zh: "令人讨厌的;恶劣的;下流的" }],
    "nerve": [{ pos: "n.", zh: "神经;勇气;胆量;紧张" }],
    "never": [{ pos: "adv.", zh: "从不;决不;从来没有" }],
    "newly": [{ pos: "adv.", zh: "最近;新近;重新" }],
    "night": [{ pos: "n.", zh: "夜晚;夜间;黑夜" }],
    "noble": [{ pos: "adj.", zh: "高尚的;贵族的;宏伟的" }, { pos: "n.", zh: "贵族" }],
    "noise": [{ pos: "n.", zh: "噪音;喧闹声;响声" }],
    "noisy": [{ pos: "adj.", zh: "嘈杂的;喧闹的" }],
    "north": [{ pos: "n.", zh: "北方;北部" }, { pos: "adj.", zh: "北方的" }, { pos: "adv.", zh: "向北方" }],
    "noted": [{ pos: "adj.", zh: "著名的;知名的;显著的" }],
    "novel": [{ pos: "n.", zh: "小说" }, { pos: "adj.", zh: "新颖的;新奇的" }],
    "nurse": [{ pos: "n.", zh: "护士;保姆;保育员" }, { pos: "v.", zh: "护理;看护;哺乳" }],
    "occur": [{ pos: "v.", zh: "发生;出现;被想到" }],
    "ocean": [{ pos: "n.", zh: "海洋;大海;大量" }],
    "offer": [{ pos: "v.", zh: "提供;提出;给予;出价" }, { pos: "n.", zh: "提议;报价;供应" }],
    "often": [{ pos: "adv.", zh: "经常;常常;通常" }],
    "onion": [{ pos: "n.", zh: "洋葱;洋葱头" }],
    "opera": [{ pos: "n.", zh: "歌剧;歌剧艺术" }],
    "order": [{ pos: "n.", zh: "顺序;命令;订单;秩序;点菜" }, { pos: "v.", zh: "命令;订购;点菜;整理" }],
    "organ": [{ pos: "n.", zh: "器官;机构;风琴" }],
    "other": [{ pos: "adj.", zh: "其他的;另外的;另一个" }, { pos: "pron.", zh: "其他人或事物" }],
    "ought": [{ pos: "aux.", zh: "应当;应该" }],
    "outer": [{ pos: "adj.", zh: "外部的;外面的;远离中心的" }],
    "owner": [{ pos: "n.", zh: "所有者;物主;业主" }],
    "paint": [{ pos: "n.", zh: "油漆;涂料;颜料" }, { pos: "v.", zh: "油漆;绘画;涂" }],
    "panel": [{ pos: "n.", zh: "面板;镶板;专门小组;控制板" }],
    "panic": [{ pos: "n.", zh: "恐慌;惊慌" }, { pos: "v.", zh: "使恐慌;惊慌失措" }],
    "paper": [{ pos: "n.", zh: "纸;报纸;论文;试卷;文件" }],
    "party": [{ pos: "n.", zh: "聚会;政党;一方;当事人" }],
    "paste": [{ pos: "n.", zh: "糊;浆糊;面团;膏" }, { pos: "v.", zh: "粘贴;糊" }],
    "patch": [{ pos: "n.", zh: "补丁;小块;斑点;眼罩" }, { pos: "v.", zh: "修补;打补丁" }],
    "pause": [{ pos: "v.", zh: "暂停;停顿;犹豫" }, { pos: "n.", zh: "暂停;停顿" }],
    "peace": [{ pos: "n.", zh: "和平;安宁;平静" }],
    "pearl": [{ pos: "n.", zh: "珍珠;珠状物" }],
    "penny": [{ pos: "n.", zh: "便士;分(硬币)" }],
    "phase": [{ pos: "n.", zh: "阶段;时期;相位" }],
    "phone": [{ pos: "n.", zh: "电话;电话机" }, { pos: "v.", zh: "打电话" }],
    "photo": [{ pos: "n.", zh: "照片;相片" }],
    "piano": [{ pos: "n.", zh: "钢琴" }],
    "piece": [{ pos: "n.", zh: "片;块;件;篇;作品;硬币" }],
    "pilot": [{ pos: "n.", zh: "飞行员;领航员;试验性的" }, { pos: "v.", zh: "驾驶;领航;试验" }],
    "pitch": [{ pos: "n.", zh: "音高;程度;球场;沥青;投球" }, { pos: "v.", zh: "投掷;搭(帐篷);定音高;推销" }],
    "place": [{ pos: "n.", zh: "地方;地点;位置;职位" }, { pos: "v.", zh: "放置;安放;安排;下单" }],
    "plain": [{ pos: "adj.", zh: "平的;朴素的;清楚的;普通的" }, { pos: "n.", zh: "平原" }],
    "plane": [{ pos: "n.", zh: "飞机;平面;刨子" }, { pos: "adj.", zh: "平的;平面的" }],
    "plant": [{ pos: "n.", zh: "植物;工厂;设备" }, { pos: "v.", zh: "种植;栽种;安放" }],
    "plate": [{ pos: "n.", zh: "盘子;碟子;板;车牌" }],
    "plead": [{ pos: "v.", zh: "恳求;辩护;申诉" }],
    "plenty": [{ pos: "pron.", zh: "大量;充足;丰富" }, { pos: "n.", zh: "充裕;大量" }],
    "point": [{ pos: "n.", zh: "点;要点;观点;分数;尖端;时刻" }, { pos: "v.", zh: "指向;指出;瞄准" }],
    "poison": [{ pos: "n.", zh: "毒药;毒物;毒素" }, { pos: "v.", zh: "毒害;下毒;污染" }],
    "polar": [{ pos: "adj.", zh: "极地的;极的;两极的;截然相反的" }],
    "polite": [{ pos: "adj.", zh: "有礼貌的;客气的;文雅的" }],
    "pound": [{ pos: "n.", zh: "磅;英镑;重击" }, { pos: "v.", zh: "猛击;重敲;捣碎" }],
    "power": [{ pos: "n.", zh: "力量;权力;电力;能力;强国" }],
    "press": [{ pos: "v.", zh: "按;压;挤;催促;印刷" }, { pos: "n.", zh: "新闻界;出版社;按压" }],
    "price": [{ pos: "n.", zh: "价格;价钱;代价" }],
    "pride": [{ pos: "n.", zh: "骄傲;自豪;自尊" }],
    "prime": [{ pos: "adj.", zh: "首要的;主要的;最好的;素数的" }, { pos: "n.", zh: "全盛时期;质数" }],
    "print": [{ pos: "v.", zh: "印刷;打印;出版;刊登" }, { pos: "n.", zh: "印刷品;打印;字体;指纹" }],
    "prior": [{ pos: "adj.", zh: "先前的;优先的;在前的" }],
    "prize": [{ pos: "n.", zh: "奖品;奖金;奖赏" }, { pos: "adj.", zh: "获奖的;一流的" }],
    "proof": [{ pos: "n.", zh: "证据;证明;校样" }],
    "proud": [{ pos: "adj.", zh: "自豪的;骄傲的;自尊的" }],
    "prove": [{ pos: "v.", zh: "证明;证实;结果是" }],
    "pulse": [{ pos: "n.", zh: "脉搏;脉冲;搏动" }],
    "pupil": [{ pos: "n.", zh: "学生;小学生;瞳孔" }],
    "purse": [{ pos: "n.", zh: "钱包;手提包" }],
    "queen": [{ pos: "n.", zh: "女王;王后;(纸牌)王后;(棋)后" }],
    "quick": [{ pos: "adj.", zh: "快的;迅速的;敏捷的" }, { pos: "adv.", zh: "快速地" }],
    "quiet": [{ pos: "adj.", zh: "安静的;平静的;宁静的" }, { pos: "n.", zh: "安静;宁静" }],
    "quite": [{ pos: "adv.", zh: "相当;十分;完全;的确" }],
    "quote": [{ pos: "v.", zh: "引用;引述;报价" }, { pos: "n.", zh: "引文;报价" }],
    "radio": [{ pos: "n.", zh: "收音机;无线电;广播" }],
    "raise": [{ pos: "v.", zh: "举起;提高;筹集;抚养;种植" }, { pos: "n.", zh: "加薪;提高" }],
    "range": [{ pos: "n.", zh: "范围;幅度;山脉;射程;一系列" }, { pos: "v.", zh: "变化;排列;漫游" }],
    "rapid": [{ pos: "adj.", zh: "迅速的;快速的;急促的" }],
    "reach": [{ pos: "v.", zh: "到达;抵达;达到;伸手够到;联系" }, { pos: "n.", zh: "范围;到达" }],
    "react": [{ pos: "v.", zh: "反应;作出反应;起作用;反抗" }],
    "ready": [{ pos: "adj.", zh: "准备好的;乐意的;迅速的" }],
    "refer": [{ pos: "v.", zh: "提到;参考;涉及;提交" }],
    "reign": [{ pos: "n.", zh: "统治;在位期;支配" }, { pos: "v.", zh: "统治;盛行;占主导" }],
    "relax": [{ pos: "v.", zh: "放松;休息;缓和;放宽" }],
    "reply": [{ pos: "v.", zh: "回答;答复;回应" }, { pos: "n.", zh: "回答;答复" }],
    "right": [{ pos: "adj.", zh: "正确的;右边的;恰当的;健康的" }, { pos: "n.", zh: "权利;右边;正确" }, { pos: "adv.", zh: "向右;正确地;立即" }],
    "rigid": [{ pos: "adj.", zh: "僵硬的;严格的;死板的" }],
    "rival": [{ pos: "n.", zh: "竞争对手;敌手" }, { pos: "adj.", zh: "竞争的" }, { pos: "v.", zh: "与…竞争;匹敌" }],
    "river": [{ pos: "n.", zh: "河;江;河流" }],
    "roast": [{ pos: "v.", zh: "烤;烘;焙" }, { pos: "n.", zh: "烤肉" }, { pos: "adj.", zh: "烤过的" }],
    "robot": [{ pos: "n.", zh: "机器人" }],
    "rough": [{ pos: "adj.", zh: "粗糙的;粗鲁的;粗略的;艰难的" }],
    "round": [{ pos: "adj.", zh: "圆的;球形的;整数的" }, { pos: "n.", zh: "一轮;一回合;圆" }, { pos: "prep.", zh: "围绕;在…周围" }],
    "route": [{ pos: "n.", zh: "路线;路途;途径" }],
    "royal": [{ pos: "adj.", zh: "王室的;皇家的;盛大的" }],
    "ruler": [{ pos: "n.", zh: "统治者;尺子" }],
    "rural": [{ pos: "adj.", zh: "农村的;乡村的;田园的" }],
    "salad": [{ pos: "n.", zh: "色拉;沙拉" }],
    "salty": [{ pos: "adj.", zh: "咸的;含盐的;海水的" }],
    "scale": [{ pos: "n.", zh: "规模;刻度;天平;鳞片;音阶" }, { pos: "v.", zh: "攀登;按比例缩放" }],
    "scene": [{ pos: "n.", zh: "场景;场面;现场;景色;一幕" }],
    "scent": [{ pos: "n.", zh: "气味;香味;线索;嗅觉" }],
    "scope": [{ pos: "n.", zh: "范围;领域;余地;眼界" }],
    "score": [{ pos: "n.", zh: "分数;得分;乐谱;二十" }, { pos: "v.", zh: "得分;评分;获得" }],
    "seize": [{ pos: "v.", zh: "抓住;夺取;逮捕;把握" }],
    "sense": [{ pos: "n.", zh: "感觉;意义;理智;感官" }, { pos: "v.", zh: "感觉到;意识到" }],
    "serve": [{ pos: "v.", zh: "服务;招待;供应;任职;发球" }],
    "seven": [{ pos: "num.", zh: "七;七个" }],
    "shade": [{ pos: "n.", zh: "阴影;阴凉处;色调;遮阳物" }],
    "shake": [{ pos: "v.", zh: "摇动;震动;发抖;握手" }, { pos: "n.", zh: "摇动;震动;奶昔" }],
    "shall": [{ pos: "aux.", zh: "将要;会;应该;可以" }],
    "shame": [{ pos: "n.", zh: "羞耻;羞愧;遗憾" }],
    "shape": [{ pos: "n.", zh: "形状;外形;状态" }, { pos: "v.", zh: "塑造;成形;影响" }],
    "share": [{ pos: "v.", zh: "分享;共享;分担;分配" }, { pos: "n.", zh: "份额;股份;分享" }],
    "sharp": [{ pos: "adj.", zh: "锋利的;尖锐的;敏锐的;急剧的;刺耳的" }],
    "sheep": [{ pos: "n.", zh: "羊;绵羊" }],
    "sheet": [{ pos: "n.", zh: "床单;一张(纸);薄片;表格" }],
    "shelf": [{ pos: "n.", zh: "架子;搁板;大陆架" }],
    "shell": [{ pos: "n.", zh: "壳;贝壳;外壳;炮弹" }],
    "shift": [{ pos: "v.", zh: "转移;移动;改变;换班" }, { pos: "n.", zh: "转变;轮班;换挡" }],
    "shine": [{ pos: "v.", zh: "发光;照耀;出色" }, { pos: "n.", zh: "光泽;擦亮" }],
    "shirt": [{ pos: "n.", zh: "衬衫;衬衣" }],
    "shock": [{ pos: "n.", zh: "震惊;打击;休克;电击" }, { pos: "v.", zh: "使震惊;使震动" }],
    "shoot": [{ pos: "v.", zh: "射击;发射;射门;拍摄;发芽" }, { pos: "n.", zh: "嫩芽;射击" }],
    "shore": [{ pos: "n.", zh: "岸;海岸;滨" }],
    "short": [{ pos: "adj.", zh: "短的;矮的;短缺的;简短的" }],
    "shout": [{ pos: "v.", zh: "呼喊;叫喊;大声说" }, { pos: "n.", zh: "呼喊;叫喊" }],
    "sight": [{ pos: "n.", zh: "视力;景象;视野;名胜;看见" }],
    "silly": [{ pos: "adj.", zh: "愚蠢的;傻的;可笑的" }],
    "since": [{ pos: "prep.", zh: "自从;从…以来" }, { pos: "conj.", zh: "自从;因为;既然" }, { pos: "adv.", zh: "此后;后来" }],
    "sixty": [{ pos: "num.", zh: "六十" }],
    "skill": [{ pos: "n.", zh: "技能;技巧;本领" }],
    "slave": [{ pos: "n.", zh: "奴隶;受控制的人" }],
    "sleep": [{ pos: "v.", zh: "睡觉;入睡" }, { pos: "n.", zh: "睡眠;睡觉" }],
    "slice": [{ pos: "n.", zh: "薄片;切片;部分" }, { pos: "v.", zh: "切成薄片;切开" }],
    "slide": [{ pos: "v.", zh: "滑动;滑行;下滑" }, { pos: "n.", zh: "幻灯片;滑梯;滑动" }],
    "smart": [{ pos: "adj.", zh: "聪明的;智能的;时髦的;机敏的" }],
    "smell": [{ pos: "v.", zh: "闻;嗅;有…气味" }, { pos: "n.", zh: "气味;嗅觉" }],
    "smile": [{ pos: "v.", zh: "微笑;露出笑容" }, { pos: "n.", zh: "微笑;笑容" }],
    "smoke": [{ pos: "n.", zh: "烟;烟雾;吸烟" }, { pos: "v.", zh: "冒烟;吸烟;熏制" }],
    "snake": [{ pos: "n.", zh: "蛇" }],
    "solar": [{ pos: "adj.", zh: "太阳的;太阳能的" }],
    "solid": [{ pos: "adj.", zh: "固体的;实心的;坚固的;可靠的" }, { pos: "n.", zh: "固体" }],
    "solve": [{ pos: "v.", zh: "解决;解答;求解" }],
    "sorry": [{ pos: "adj.", zh: "抱歉的;遗憾的;难过的" }],
    "sound": [{ pos: "n.", zh: "声音;响声" }, { pos: "v.", zh: "听起来;发声" }, { pos: "adj.", zh: "合理的;健全的;完好的" }],
    "south": [{ pos: "n.", zh: "南方;南部" }, { pos: "adj.", zh: "南方的" }, { pos: "adv.", zh: "向南方" }],
    "space": [{ pos: "n.", zh: "空间;太空;空地;空白;间隔" }],
    "spare": [{ pos: "adj.", zh: "空闲的;备用的;多余的" }, { pos: "v.", zh: "节省;抽出(时间);饶恕" }],
    "speak": [{ pos: "v.", zh: "说话;讲话;发言;会说(语言)" }],
    "speed": [{ pos: "n.", zh: "速度;快速;速率" }, { pos: "v.", zh: "加速;疾行;超速" }],
    "spell": [{ pos: "v.", zh: "拼写;拼出;意味着;招致" }, { pos: "n.", zh: "咒语;一段时间" }],
    "spend": [{ pos: "v.", zh: "花费;度过;消耗" }],
    "spite": [{ pos: "n.", zh: "恶意;怨恨" }],
    "split": [{ pos: "v.", zh: "分裂;分开;劈开;分摊" }, { pos: "n.", zh: "分裂;分歧;份额" }],
    "spoil": [{ pos: "v.", zh: "破坏;宠坏;变质;溺爱" }],
    "sport": [{ pos: "n.", zh: "运动;体育;体育活动" }],
    "staff": [{ pos: "n.", zh: "全体职员;工作人员;棍棒;五线谱" }],
    "stage": [{ pos: "n.", zh: "舞台;阶段;时期;讲台" }, { pos: "v.", zh: "上演;举办;组织" }],
    "stain": [{ pos: "n.", zh: "污渍;污点;染色剂" }, { pos: "v.", zh: "弄脏;染色" }],
    "stair": [{ pos: "n.", zh: "楼梯;阶梯" }],
    "stamp": [{ pos: "n.", zh: "邮票;印章;印记" }, { pos: "v.", zh: "盖章;跺脚;贴邮票" }],
    "stand": [{ pos: "v.", zh: "站立;忍受;位于;保持;主张" }, { pos: "n.", zh: "立场;摊位;看台" }],
    "stare": [{ pos: "v.", zh: "凝视;盯着看" }, { pos: "n.", zh: "凝视" }],
    "start": [{ pos: "v.", zh: "开始;出发;启动;开办" }, { pos: "n.", zh: "开始;起点;开端" }],
    "state": [{ pos: "n.", zh: "状态;国家;州;政府" }, { pos: "v.", zh: "陈述;声明;说明" }],
    "steal": [{ pos: "v.", zh: "偷;窃取;偷偷地移动" }],
    "steam": [{ pos: "n.", zh: "蒸汽;水汽" }, { pos: "v.", zh: "蒸;冒热气" }],
    "steel": [{ pos: "n.", zh: "钢;钢铁" }],
    "steep": [{ pos: "adj.", zh: "陡峭的;急剧的;过高的" }],
    "stick": [{ pos: "n.", zh: "棍;棒;枝条" }, { pos: "v.", zh: "粘贴;刺;卡住;坚持" }],
    "stiff": [{ pos: "adj.", zh: "僵硬的;生硬的;费劲的" }],
    "still": [{ pos: "adv.", zh: "仍然;还;依旧;更加" }, { pos: "adj.", zh: "静止的;平静的" }],
    "stock": [{ pos: "n.", zh: "股票;库存;存货;牲畜" }, { pos: "v.", zh: "储备;存货" }],
    "stone": [{ pos: "n.", zh: "石头;石块;宝石;果核" }],
    "store": [{ pos: "n.", zh: "商店;店铺;储存;仓库" }, { pos: "v.", zh: "储存;存储;储备" }],
    "storm": [{ pos: "n.", zh: "暴风雨;风暴;爆发" }, { pos: "v.", zh: "猛攻;怒吼;暴怒" }],
    "story": [{ pos: "n.", zh: "故事;小说;报道;楼层" }],
    "stove": [{ pos: "n.", zh: "炉子;火炉;灶" }],
    "straw": [{ pos: "n.", zh: "稻草;麦秆;吸管" }],
    "stress": [{ pos: "n.", zh: "压力;紧张;强调;重音" }, { pos: "v.", zh: "强调;使紧张;重读" }],
    "strike": [{ pos: "v.", zh: "打击;罢工;袭击;打动;敲" }, { pos: "n.", zh: "罢工;打击;袭击" }],
    "strip": [{ pos: "v.", zh: "剥去;脱去;剥夺" }, { pos: "n.", zh: "条;带;长条" }],
    "stroke": [{ pos: "n.", zh: "中风;笔画;一击;抚摸;泳姿" }, { pos: "v.", zh: "抚摸;轻触" }],
    "strong": [{ pos: "adj.", zh: "强壮的;坚固的;强烈的;擅长的" }],
    "study": [{ pos: "v.", zh: "学习;研究;细察" }, { pos: "n.", zh: "学习;研究;书房" }],
    "stuff": [{ pos: "n.", zh: "东西;物品;材料;填充物" }, { pos: "v.", zh: "填塞;装满" }],
    "style": [{ pos: "n.", zh: "风格;样式;方式;时尚" }],
    "sugar": [{ pos: "n.", zh: "糖;食糖" }],
    "sunny": [{ pos: "adj.", zh: "阳光充足的;晴朗的;快活的" }],
    "super": [{ pos: "adj.", zh: "极好的;超级的;特级的" }],
    "sweep": [{ pos: "v.", zh: "扫;清扫;掠过;席卷" }],
    "sweet": [{ pos: "adj.", zh: "甜的;芳香的;可爱的;悦耳的" }, { pos: "n.", zh: "糖果;甜点" }],
    "swing": [{ pos: "v.", zh: "摇摆;摆动;旋转;荡秋千" }, { pos: "n.", zh: "摆动;秋千;转变" }],
    "sword": [{ pos: "n.", zh: "剑;刀" }],
    "table": [{ pos: "n.", zh: "桌子;表格;一览表" }],
    "taste": [{ pos: "n.", zh: "味道;品味;爱好;品尝" }, { pos: "v.", zh: "品尝;尝起来;体验" }],
    "teach": [{ pos: "v.", zh: "教;教导;讲授;教训" }],
    "teeth": [{ pos: "n.", zh: "tooth 的复数(牙齿)" }],
    "thank": [{ pos: "v.", zh: "感谢;谢谢" }],
    "theme": [{ pos: "n.", zh: "主题;题目;主旋律" }],
    "there": [{ pos: "adv.", zh: "在那里;往那里;存在" }],
    "these": [{ pos: "pron.", zh: "这些" }, { pos: "adj.", zh: "这些的" }],
    "thick": [{ pos: "adj.", zh: "厚的;粗的;浓的;密集的" }],
    "thief": [{ pos: "n.", zh: "小偷;贼" }],
    "thing": [{ pos: "n.", zh: "东西;事情;事物;局面" }],
    "think": [{ pos: "v.", zh: "想;思考;认为;考虑" }],
    "third": [{ pos: "num.", zh: "第三" }, { pos: "n.", zh: "三分之一" }],
    "those": [{ pos: "pron.", zh: "那些" }, { pos: "adj.", zh: "那些的" }],
    "three": [{ pos: "num.", zh: "三;三个" }],
    "throw": [{ pos: "v.", zh: "扔;投;抛;掷" }, { pos: "n.", zh: "投掷;抛" }],
    "thumb": [{ pos: "n.", zh: "拇指" }],
    "tiger": [{ pos: "n.", zh: "老虎" }],
    "tight": [{ pos: "adj.", zh: "紧的;牢固的;紧身的;严密的" }],
    "tired": [{ pos: "adj.", zh: "疲倦的;疲劳的;厌倦的" }],
    "title": [{ pos: "n.", zh: "标题;题目;称号;头衔;所有权" }],
    "today": [{ pos: "adv.", zh: "今天;现在;当今" }, { pos: "n.", zh: "今天;当今" }],
    "tooth": [{ pos: "n.", zh: "牙齿;齿" }],
    "topic": [{ pos: "n.", zh: "话题;主题;题目" }],
    "total": [{ pos: "adj.", zh: "总的;全部的;完全的" }, { pos: "n.", zh: "总数;合计" }, { pos: "v.", zh: "总计;合计" }],
    "touch": [{ pos: "v.", zh: "触摸;接触;感动;涉及" }, { pos: "n.", zh: "触摸;接触;联系" }],
    "tough": [{ pos: "adj.", zh: "坚韧的;坚强的;艰难的;强硬的" }],
    "tower": [{ pos: "n.", zh: "塔;高楼;塔楼" }],
    "trace": [{ pos: "v.", zh: "追踪;追溯;描绘" }, { pos: "n.", zh: "痕迹;踪迹;微量" }],
    "track": [{ pos: "n.", zh: "轨道;跑道;踪迹;路线;歌曲" }, { pos: "v.", zh: "追踪;跟踪;留下足迹" }],
    "trade": [{ pos: "n.", zh: "贸易;交易;行业;职业" }, { pos: "v.", zh: "交易;贸易;交换" }],
    "trail": [{ pos: "n.", zh: "小径;痕迹;踪迹" }, { pos: "v.", zh: "拖;追踪;落后" }],
    "train": [{ pos: "n.", zh: "火车;列车;行列" }, { pos: "v.", zh: "训练;培训;锻炼" }],
    "treat": [{ pos: "v.", zh: "对待;处理;治疗;款待;请客" }, { pos: "n.", zh: "款待;乐事" }],
    "trend": [{ pos: "n.", zh: "趋势;倾向;潮流" }],
    "trial": [{ pos: "n.", zh: "审判;试验;试用;磨难" }],
    "tribe": [{ pos: "n.", zh: "部落;宗族;群" }],
    "trick": [{ pos: "n.", zh: "诡计;花招;戏法;诀窍" }, { pos: "v.", zh: "欺骗;戏弄" }],
    "troop": [{ pos: "n.", zh: "军队;部队;一群" }],
    "truck": [{ pos: "n.", zh: "卡车;货车" }],
    "truly": [{ pos: "adv.", zh: "真正地;真诚地;确实地" }],
    "trust": [{ pos: "v.", zh: "信任;相信;信赖" }, { pos: "n.", zh: "信任;信赖;托拉斯" }],
    "truth": [{ pos: "n.", zh: "真相;事实;真理;真实性" }],
    "twice": [{ pos: "adv.", zh: "两次;两倍" }],
    "uncle": [{ pos: "n.", zh: "叔叔;伯父;舅舅;姑父;姨父" }],
    "under": [{ pos: "prep.", zh: "在…下面;低于;在…情况下" }, { pos: "adv.", zh: "在下面;在水下" }],
    "union": [{ pos: "n.", zh: "工会;联盟;联合;联合会" }],
    "unite": [{ pos: "v.", zh: "联合;团结;统一;结合" }],
    "until": [{ pos: "prep.", zh: "直到;到…为止" }, { pos: "conj.", zh: "直到…才" }],
    "upper": [{ pos: "adj.", zh: "上面的;较高的;上层的" }],
    "upset": [{ pos: "v.", zh: "使心烦;打乱;打翻" }, { pos: "adj.", zh: "心烦的;难过的;不适的" }],
    "urban": [{ pos: "adj.", zh: "城市的;都市的" }],
    "usual": [{ pos: "adj.", zh: "通常的;平常的;惯常的" }],
    "utter": [{ pos: "v.", zh: "说出;发出(声音)" }, { pos: "adj.", zh: "完全的;彻底的" }],
    "valid": [{ pos: "adj.", zh: "有效的;正当的;合法的" }],
    "value": [{ pos: "n.", zh: "价值;价格;重要性;价值观" }, { pos: "v.", zh: "重视;估价" }],
    "video": [{ pos: "n.", zh: "视频;录像;录像带" }, { pos: "adj.", zh: "视频的;录像的" }],
    "virus": [{ pos: "n.", zh: "病毒;计算机病毒" }],
    "visit": [{ pos: "v.", zh: "参观;访问;拜访;探望" }, { pos: "n.", zh: "参观;访问;拜访" }],
    "vital": [{ pos: "adj.", zh: "至关重要的;生死攸关的;有活力的" }],
    "vivid": [{ pos: "adj.", zh: "生动的;鲜明的;活泼的" }],
    "voice": [{ pos: "n.", zh: "声音;嗓音;意见;语态" }],
    "voter": [{ pos: "n.", zh: "投票人;选举人;选民" }],
    "waste": [{ pos: "v.", zh: "浪费;滥用;消耗" }, { pos: "n.", zh: "浪费;废物;垃圾" }, { pos: "adj.", zh: "废弃的;无用的" }],
    "watch": [{ pos: "v.", zh: "观看;注视;监视;当心" }, { pos: "n.", zh: "手表;监视;看守" }],
    "water": [{ pos: "n.", zh: "水;雨水;水域" }, { pos: "v.", zh: "浇水;给…供水" }],
    "weave": [{ pos: "v.", zh: "编织;织;编造" }],
    "weigh": [{ pos: "v.", zh: "称…重量;重达;权衡" }],
    "weird": [{ pos: "adj.", zh: "奇怪的;怪异的;不可思议的" }],
    "wheel": [{ pos: "n.", zh: "轮子;车轮;方向盘" }],
    "where": [{ pos: "adv.", zh: "在哪里;到哪里;…的地方" }, { pos: "conj.", zh: "在…的地方" }],
    "which": [{ pos: "pron.", zh: "哪一个;哪些" }, { pos: "adj.", zh: "哪一个;哪一些" }],
    "while": [{ pos: "conj.", zh: "当…的时候;虽然;而" }, { pos: "n.", zh: "一段时间" }],
    "white": [{ pos: "adj.", zh: "白色的;白的;苍白的" }, { pos: "n.", zh: "白色" }],
    "whole": [{ pos: "adj.", zh: "整个的;全部的;完整的" }, { pos: "n.", zh: "整体;全部" }],
    "whose": [{ pos: "pron.", zh: "谁的;…的" }],
    "width": [{ pos: "n.", zh: "宽度;广度;幅度" }],
    "winter": [{ pos: "n.", zh: "冬天;冬季" }],
    "wisdom": [{ pos: "n.", zh: "智慧;才智;明智" }],
    "witch": [{ pos: "n.", zh: "女巫;巫婆" }],
    "woman": [{ pos: "n.", zh: "妇女;女人;女性" }],
    "wonder": [{ pos: "v.", zh: "想知道;惊奇;疑惑" }, { pos: "n.", zh: "惊奇;奇迹;奇观" }],
    "wooden": [{ pos: "adj.", zh: "木制的;呆板的" }],
    "worse": [{ pos: "adj.", zh: "更坏的;更糟的" }, { pos: "adv.", zh: "更坏;更糟" }],
    "worst": [{ pos: "adj.", zh: "最坏的;最差的" }, { pos: "adv.", zh: "最坏;最差" }],
    "worth": [{ pos: "adj.", zh: "值得的;值…钱的" }, { pos: "n.", zh: "价值;意义" }],
    "wound": [{ pos: "n.", zh: "伤口;创伤;伤害" }, { pos: "v.", zh: "使受伤;伤害" }],
    "write": [{ pos: "v.", zh: "写;书写;写作;写信" }],
    "wrong": [{ pos: "adj.", zh: "错误的;不对的;不道德的" }, { pos: "adv.", zh: "错误地" }, { pos: "n.", zh: "错误;坏事" }],
    "yield": [{ pos: "v.", zh: "产生;产出;屈服;让步;让行" }, { pos: "n.", zh: "产量;收益" }],
    "young": [{ pos: "adj.", zh: "年轻的;幼小的" }, { pos: "n.", zh: "年轻人" }],
    "youth": [{ pos: "n.", zh: "青年;青春;年轻人;青年时期" }],
};
