/*
 * p了个s · 英了个语 词库释义 (src/game2/meanings.ts)
 * ===================================================
 * 每个词: 词性与中文释义(多词性/多义项全部列出)。
 * 生成器只从「有释义的词」中取词, 保证对局内每个词都能在结算页
 * 逐条查看词性与释义。词性标记: n.名词 v.动词 adj.形容词 adv.副词 prep.介词 conj.连词 num.数词 pron.代词 art.冠词 int.感叹词 aux.助动词
 */
export const WS_MEANINGS: Record<string, { pos: string; zh: string }[]> = {
    // ==================== 4 字母 ====================
    "able": [{ pos: "adj.", zh: "能够的;有能力的" }],
    "acid": [{ pos: "n.", zh: "酸" }, { pos: "adj.", zh: "酸的" }],
    "area": [{ pos: "n.", zh: "地区;面积;领域" }],
    "army": [{ pos: "n.", zh: "军队;陆军" }],
    "baby": [{ pos: "n.", zh: "婴儿;幼崽" }],
    "back": [{ pos: "n.", zh: "背部;后面" }, { pos: "adv.", zh: "向后;回原处" }, { pos: "v.", zh: "支持;后退" }],
    "bake": [{ pos: "v.", zh: "烘烤;焙" }],
    "ball": [{ pos: "n.", zh: "球;舞会" }],
    "band": [{ pos: "n.", zh: "乐队;带子;波段" }],
    "bank": [{ pos: "n.", zh: "银行;河岸" }],
    "bare": [{ pos: "adj.", zh: "赤裸的;空的" }],
    "base": [{ pos: "n.", zh: "基础;基地;底部" }, { pos: "v.", zh: "以…为基础" }],
    "bath": [{ pos: "n.", zh: "洗澡;浴缸" }],
    "bear": [{ pos: "n.", zh: "熊" }, { pos: "v.", zh: "忍受;承受;生育" }],
    "beat": [{ pos: "v.", zh: "打败;敲打;跳动" }, { pos: "n.", zh: "节拍;敲击" }],
    "bell": [{ pos: "n.", zh: "铃;钟" }],
    "belt": [{ pos: "n.", zh: "腰带;皮带;地带" }],
    "bend": [{ pos: "v.", zh: "弯曲;弯腰" }, { pos: "n.", zh: "弯曲处" }],
    "best": [{ pos: "adj.", zh: "最好的" }, { pos: "adv.", zh: "最好地" }],
    "bill": [{ pos: "n.", zh: "账单;法案;钞票" }],
    "bind": [{ pos: "v.", zh: "捆绑;约束;装订" }],
    "bird": [{ pos: "n.", zh: "鸟" }],
    "bite": [{ pos: "v.", zh: "咬;叮" }, { pos: "n.", zh: "咬;一口" }],
    "blue": [{ pos: "adj.", zh: "蓝色的;忧郁的" }, { pos: "n.", zh: "蓝色" }],
    "boat": [{ pos: "n.", zh: "小船;艇" }],
    "body": [{ pos: "n.", zh: "身体;主体;尸体" }],
    "boil": [{ pos: "v.", zh: "煮沸;沸腾" }],
    "bold": [{ pos: "adj.", zh: "大胆的;粗体的" }],
    "bomb": [{ pos: "n.", zh: "炸弹" }, { pos: "v.", zh: "轰炸" }],
    "bone": [{ pos: "n.", zh: "骨头;骨骼" }],
    "book": [{ pos: "n.", zh: "书;书籍" }, { pos: "v.", zh: "预订" }],
    "boot": [{ pos: "n.", zh: "靴子;(车)后备箱" }],
    "bore": [{ pos: "v.", zh: "使厌烦;钻孔" }, { pos: "n.", zh: "令人厌烦的人或事" }],
    "born": [{ pos: "adj.", zh: "出生的;天生的" }],
    "boss": [{ pos: "n.", zh: "老板;上司" }],
    "both": [{ pos: "pron.", zh: "两者都" }, { pos: "adj.", zh: "两个…都" }],
    "bowl": [{ pos: "n.", zh: "碗;碗状物" }],
    "burn": [{ pos: "v.", zh: "燃烧;烧伤" }, { pos: "n.", zh: "烧伤" }],
    "bury": [{ pos: "v.", zh: "埋葬;掩埋" }],
    "busy": [{ pos: "adj.", zh: "忙碌的;繁忙的" }],
    "cake": [{ pos: "n.", zh: "蛋糕;饼" }],
    "call": [{ pos: "v.", zh: "打电话;称呼;叫喊" }, { pos: "n.", zh: "电话;呼叫" }],
    "calm": [{ pos: "adj.", zh: "平静的;镇定的" }, { pos: "v.", zh: "使平静" }],
    "camp": [{ pos: "n.", zh: "营地;帐篷" }, { pos: "v.", zh: "露营" }],
    "card": [{ pos: "n.", zh: "卡片;纸牌;明信片" }],
    "care": [{ pos: "n.", zh: "照顾;小心;关心" }, { pos: "v.", zh: "在意;照顾" }],
    "case": [{ pos: "n.", zh: "情况;案例;箱子;病例" }],
    "cash": [{ pos: "n.", zh: "现金;现款" }],
    "cast": [{ pos: "v.", zh: "投掷;铸造;选派角色" }, { pos: "n.", zh: "演员阵容" }],
    "cave": [{ pos: "n.", zh: "洞穴;山洞" }],
    "cell": [{ pos: "n.", zh: "细胞;电池;牢房;单元" }],
    "chat": [{ pos: "v.", zh: "聊天;闲谈" }, { pos: "n.", zh: "聊天" }],
    "city": [{ pos: "n.", zh: "城市;都市" }],
    "coal": [{ pos: "n.", zh: "煤;煤炭" }],
    "coat": [{ pos: "n.", zh: "外套;涂层" }, { pos: "v.", zh: "给…涂上" }],
    "code": [{ pos: "n.", zh: "代码;密码;法典" }],
    "coin": [{ pos: "n.", zh: "硬币;钱币" }],
    "cold": [{ pos: "adj.", zh: "寒冷的;冷淡的" }, { pos: "n.", zh: "感冒;寒冷" }],
    "come": [{ pos: "v.", zh: "来;到来;出现" }],
    "cook": [{ pos: "v.", zh: "烹饪;做饭" }, { pos: "n.", zh: "厨师" }],
    "cool": [{ pos: "adj.", zh: "凉爽的;酷的;冷静的" }, { pos: "v.", zh: "使冷却" }],
    "copy": [{ pos: "n.", zh: "副本;复制品;一份" }, { pos: "v.", zh: "复制;抄袭" }],
    "corn": [{ pos: "n.", zh: "玉米;谷物" }],
    "cost": [{ pos: "n.", zh: "成本;费用" }, { pos: "v.", zh: "花费" }],
    "crop": [{ pos: "n.", zh: "庄稼;收成;一批" }],
    "cure": [{ pos: "v.", zh: "治愈;治疗" }, { pos: "n.", zh: "疗法;药物" }],
    "dark": [{ pos: "adj.", zh: "黑暗的;深色的" }, { pos: "n.", zh: "黑暗" }],
    "date": [{ pos: "n.", zh: "日期;约会;枣" }, { pos: "v.", zh: "注明日期;约会" }],
    "dawn": [{ pos: "n.", zh: "黎明;拂晓" }],
    "dead": [{ pos: "adj.", zh: "死的;麻木的;完全的" }],
    "deal": [{ pos: "n.", zh: "交易;协议" }, { pos: "v.", zh: "处理;应付;经营" }],
    "dear": [{ pos: "adj.", zh: "亲爱的;昂贵的" }, { pos: "int.", zh: "哎呀" }],
    "debt": [{ pos: "n.", zh: "债务;欠款" }],
    "deep": [{ pos: "adj.", zh: "深的;深刻的;深沉的" }, { pos: "adv.", zh: "深深地" }],
    "deny": [{ pos: "v.", zh: "否认;拒绝给予" }],
    "desk": [{ pos: "n.", zh: "书桌;办公桌" }],
    "diet": [{ pos: "n.", zh: "日常饮食;节食" }, { pos: "v.", zh: "节食" }],
    "dirt": [{ pos: "n.", zh: "泥土;污垢" }],
    "dish": [{ pos: "n.", zh: "碟子;菜肴" }],
    "door": [{ pos: "n.", zh: "门" }],
    "down": [{ pos: "adv.", zh: "向下;下降" }, { pos: "prep.", zh: "沿着…往下" }, { pos: "adj.", zh: "沮丧的" }],
    "draw": [{ pos: "v.", zh: "画;拉;吸引;得出" }],
    "drop": [{ pos: "v.", zh: "掉落;下降;放弃" }, { pos: "n.", zh: "滴;下降" }],
    "drug": [{ pos: "n.", zh: "药;药物;毒品" }],
    "drum": [{ pos: "n.", zh: "鼓;鼓状物" }],
    "duck": [{ pos: "n.", zh: "鸭子" }, { pos: "v.", zh: "躲避;低头" }],
    "dull": [{ pos: "adj.", zh: "迟钝的;乏味的;暗淡的" }],
    "dust": [{ pos: "n.", zh: "灰尘;尘土" }],
    "duty": [{ pos: "n.", zh: "职责;义务;税" }],
    "each": [{ pos: "pron.", zh: "每个;各自" }, { pos: "adj.", zh: "各自的" }],
    "earn": [{ pos: "v.", zh: "赚得;赢得;获得" }],
    "ease": [{ pos: "n.", zh: "容易;舒适" }, { pos: "v.", zh: "减轻;缓和" }],
    "east": [{ pos: "n.", zh: "东方;东部" }, { pos: "adj.", zh: "东方的" }, { pos: "adv.", zh: "向东" }],
    "easy": [{ pos: "adj.", zh: "容易的;轻松的" }],
    "edge": [{ pos: "n.", zh: "边缘;刀刃;优势" }],
    "else": [{ pos: "adv.", zh: "其他;另外" }],
    "even": [{ pos: "adv.", zh: "甚至;即使" }, { pos: "adj.", zh: "平的;均匀的;偶数的" }],
    "ever": [{ pos: "adv.", zh: "曾经;在任何时候" }],
    "exam": [{ pos: "n.", zh: "考试;检查" }],
    "exit": [{ pos: "n.", zh: "出口;退场" }, { pos: "v.", zh: "退出;离开" }],
    "face": [{ pos: "n.", zh: "脸;表面;面临" }, { pos: "v.", zh: "面对;面向" }],
    "fact": [{ pos: "n.", zh: "事实;真相" }],
    "fade": [{ pos: "v.", zh: "褪色;逐渐消失" }],
    "fail": [{ pos: "v.", zh: "失败;不及格;未能" }],
    "fair": [{ pos: "adj.", zh: "公平的;晴朗的;相当好的" }, { pos: "n.", zh: "集市;展览会" }],
    "fall": [{ pos: "v.", zh: "落下;跌倒;下降" }, { pos: "n.", zh: "秋天;落下" }],
    "farm": [{ pos: "n.", zh: "农场;农田" }, { pos: "v.", zh: "耕作;养殖" }],
    "fast": [{ pos: "adj.", zh: "快的;迅速的" }, { pos: "adv.", zh: "快速地;牢牢地" }],
    "fate": [{ pos: "n.", zh: "命运;天命" }],
    "fear": [{ pos: "n.", zh: "恐惧;害怕" }, { pos: "v.", zh: "害怕;担心" }],
    "feed": [{ pos: "v.", zh: "喂养;饲养;供应" }, { pos: "n.", zh: "饲料" }],
    "feel": [{ pos: "v.", zh: "感觉;触摸;认为" }],
    "file": [{ pos: "n.", zh: "文件;档案;锉刀" }, { pos: "v.", zh: "归档;提交" }],
    "fill": [{ pos: "v.", zh: "装满;填满;填充" }],
    "film": [{ pos: "n.", zh: "电影;胶片;薄膜" }],
    "find": [{ pos: "v.", zh: "找到;发现;认为" }],
    "fine": [{ pos: "adj.", zh: "好的;晴朗的;精细的;罚款的" }, { pos: "n.", zh: "罚款" }],
    "fire": [{ pos: "n.", zh: "火;火灾;射击" }, { pos: "v.", zh: "开火;解雇;点燃" }],
    "firm": [{ pos: "adj.", zh: "坚定的;坚固的" }, { pos: "n.", zh: "公司;商行" }],
    "fish": [{ pos: "n.", zh: "鱼;鱼肉" }, { pos: "v.", zh: "钓鱼;捕鱼" }],
    "five": [{ pos: "num.", zh: "五;五个" }],
    "flag": [{ pos: "n.", zh: "旗帜;国旗" }],
    "flat": [{ pos: "adj.", zh: "平的;扁平的;平淡的" }, { pos: "n.", zh: "公寓" }],
    "flow": [{ pos: "v.", zh: "流动;涌出" }, { pos: "n.", zh: "流动;流量" }],
    "fold": [{ pos: "v.", zh: "折叠;合拢" }, { pos: "n.", zh: "折痕" }],
    "food": [{ pos: "n.", zh: "食物;食品" }],
    "fool": [{ pos: "n.", zh: "傻瓜;愚人" }, { pos: "v.", zh: "欺骗;愚弄" }],
    "foot": [{ pos: "n.", zh: "脚;底部;英尺" }],
    "form": [{ pos: "n.", zh: "形式;表格;形状" }, { pos: "v.", zh: "形成;组成" }],
    "free": [{ pos: "adj.", zh: "自由的;免费的;空闲的" }, { pos: "v.", zh: "释放;解放" }],
    "from": [{ pos: "prep.", zh: "从…;来自;由于" }],
    "fuel": [{ pos: "n.", zh: "燃料" }, { pos: "v.", zh: "加燃料;刺激" }],
    "full": [{ pos: "adj.", zh: "满的;完全的;吃饱的" }],
    "fund": [{ pos: "n.", zh: "基金;资金" }, { pos: "v.", zh: "资助;提供资金" }],
    "gain": [{ pos: "v.", zh: "获得;增加;赢得" }, { pos: "n.", zh: "收益;增加" }],
    "game": [{ pos: "n.", zh: "游戏;比赛;猎物" }],
    "gate": [{ pos: "n.", zh: "大门;闸门;登机口" }],
    "gift": [{ pos: "n.", zh: "礼物;天赋;赠品" }],
    "give": [{ pos: "v.", zh: "给;提供;赠送" }],
    "glad": [{ pos: "adj.", zh: "高兴的;乐意的" }],
    "goal": [{ pos: "n.", zh: "目标;球门;进球" }],
    "gold": [{ pos: "n.", zh: "黄金;金色;金牌" }, { pos: "adj.", zh: "金的;金色的" }],
    "good": [{ pos: "adj.", zh: "好的;有益的;擅长的" }, { pos: "n.", zh: "好处;善" }],
    "grab": [{ pos: "v.", zh: "抓住;夺取;匆忙地吃" }],
    "gray": [{ pos: "adj.", zh: "灰色的;阴沉的" }, { pos: "n.", zh: "灰色" }],
    "grow": [{ pos: "v.", zh: "生长;成长;种植;增加" }],
    "hair": [{ pos: "n.", zh: "头发;毛发" }],
    "half": [{ pos: "n.", zh: "一半;半个" }, { pos: "adj.", zh: "一半的" }, { pos: "adv.", zh: "一半地" }],
    "hall": [{ pos: "n.", zh: "大厅;礼堂;门厅" }],
    "hand": [{ pos: "n.", zh: "手;指针;帮助" }, { pos: "v.", zh: "递交;交给" }],
    "hang": [{ pos: "v.", zh: "悬挂;吊着;绞死" }],
    "hard": [{ pos: "adj.", zh: "硬的;困难的;辛苦的" }, { pos: "adv.", zh: "努力地;猛烈地" }],
    "harm": [{ pos: "n.", zh: "伤害;损害" }, { pos: "v.", zh: "伤害;损害" }],
    "hate": [{ pos: "v.", zh: "憎恨;讨厌" }, { pos: "n.", zh: "憎恨" }],
    "have": [{ pos: "v.", zh: "有;拥有;吃;经历" }],
    "head": [{ pos: "n.", zh: "头;头脑;领导;头部" }, { pos: "v.", zh: "朝…前进;主管" }],
    "heal": [{ pos: "v.", zh: "治愈;愈合;康复" }],
    "hear": [{ pos: "v.", zh: "听见;听说;倾听" }],
    "heat": [{ pos: "n.", zh: "热;热量;高温" }, { pos: "v.", zh: "加热" }],
    "help": [{ pos: "v.", zh: "帮助;有助于" }, { pos: "n.", zh: "帮助;援助" }],
    "hide": [{ pos: "v.", zh: "隐藏;躲避;隐瞒" }],
    "high": [{ pos: "adj.", zh: "高的;高级的;高度的" }, { pos: "adv.", zh: "高高地" }],
    "hill": [{ pos: "n.", zh: "小山;丘陵" }],
    "hire": [{ pos: "v.", zh: "雇用;租用" }, { pos: "n.", zh: "租用;雇用" }],
    "hold": [{ pos: "v.", zh: "握住;举行;容纳;保持" }, { pos: "n.", zh: "握;控制" }],
    "hole": [{ pos: "n.", zh: "洞;孔;漏洞" }],
    "holy": [{ pos: "adj.", zh: "神圣的;圣洁的" }],
    "home": [{ pos: "n.", zh: "家;家乡;家庭" }, { pos: "adv.", zh: "在家;回家" }],
    "hope": [{ pos: "v.", zh: "希望;期望" }, { pos: "n.", zh: "希望;期望" }],
    "host": [{ pos: "n.", zh: "主人;主持人;宿主" }, { pos: "v.", zh: "主办;主持" }],
    "hour": [{ pos: "n.", zh: "小时;时刻;时间" }],
    "huge": [{ pos: "adj.", zh: "巨大的;庞大的" }],
    "hunt": [{ pos: "v.", zh: "打猎;追捕;搜寻" }, { pos: "n.", zh: "狩猎;搜寻" }],
    "hurt": [{ pos: "v.", zh: "使受伤;伤害;疼痛" }, { pos: "n.", zh: "伤害" }],
    "idea": [{ pos: "n.", zh: "想法;主意;概念" }],
    "inch": [{ pos: "n.", zh: "英寸" }],
    "into": [{ pos: "prep.", zh: "进入;到…里面;变成" }],
    "iron": [{ pos: "n.", zh: "铁;熨斗" }, { pos: "v.", zh: "熨烫" }],
    "item": [{ pos: "n.", zh: "项目;物品;条款" }],
    "join": [{ pos: "v.", zh: "参加;加入;连接;结合" }],
    "joke": [{ pos: "n.", zh: "笑话;玩笑" }, { pos: "v.", zh: "开玩笑" }],
    "jump": [{ pos: "v.", zh: "跳;跃;猛涨" }, { pos: "n.", zh: "跳跃" }],
    "just": [{ pos: "adv.", zh: "刚刚;仅仅;正好" }, { pos: "adj.", zh: "公正的;正义的" }],
    "keen": [{ pos: "adj.", zh: "热心的;敏锐的;渴望的" }],
    "keep": [{ pos: "v.", zh: "保持;保留;继续;饲养" }],
    "kick": [{ pos: "v.", zh: "踢;踹" }, { pos: "n.", zh: "踢" }],
    "kill": [{ pos: "v.", zh: "杀死;扼杀;消磨(时间)" }],
    "kind": [{ pos: "n.", zh: "种类;类型" }, { pos: "adj.", zh: "仁慈的;友好的" }],
    "king": [{ pos: "n.", zh: "国王;君主;王" }],
    "kiss": [{ pos: "v.", zh: "亲吻" }, { pos: "n.", zh: "吻" }],
    "knee": [{ pos: "n.", zh: "膝盖" }],
    "know": [{ pos: "v.", zh: "知道;认识;了解" }],
    "lack": [{ pos: "n.", zh: "缺乏;不足" }, { pos: "v.", zh: "缺乏;没有" }],
    "lady": [{ pos: "n.", zh: "女士;夫人;小姐" }],
    "lake": [{ pos: "n.", zh: "湖;湖泊" }],
    "land": [{ pos: "n.", zh: "土地;陆地;国家" }, { pos: "v.", zh: "着陆;登陆;降落" }],
    "last": [{ pos: "adj.", zh: "最后的;最近的" }, { pos: "adv.", zh: "最后;上次" }, { pos: "v.", zh: "持续;维持" }],
    "late": [{ pos: "adj.", zh: "迟的;晚的;已故的" }, { pos: "adv.", zh: "迟;晚" }],
    "lead": [{ pos: "v.", zh: "带领;领导;导致;通向" }, { pos: "n.", zh: "领先;铅" }],
    "leaf": [{ pos: "n.", zh: "叶子;页" }],
    "lean": [{ pos: "v.", zh: "倾斜;倚靠;依赖" }, { pos: "adj.", zh: "瘦的;精简的" }],
    "leap": [{ pos: "v.", zh: "跳跃;猛冲" }, { pos: "n.", zh: "跳跃;飞跃" }],
    "left": [{ pos: "adj.", zh: "左边的;剩下的" }, { pos: "adv.", zh: "向左" }, { pos: "n.", zh: "左边" }],
    "lend": [{ pos: "v.", zh: "借出;贷(款);提供" }],
    "less": [{ pos: "adj.", zh: "更少的;较少的" }, { pos: "adv.", zh: "更少地" }],
    "life": [{ pos: "n.", zh: "生命;生活;一生" }],
    "lift": [{ pos: "v.", zh: "举起;抬起;升起" }, { pos: "n.", zh: "电梯;举起" }],
    "like": [{ pos: "v.", zh: "喜欢;想要" }, { pos: "prep.", zh: "像;如同" }, { pos: "adj.", zh: "相似的" }],
    "line": [{ pos: "n.", zh: "线;行;线路;台词" }],
    "link": [{ pos: "n.", zh: "联系;链接;环节" }, { pos: "v.", zh: "连接;联系" }],
    "list": [{ pos: "n.", zh: "名单;清单;列表" }, { pos: "v.", zh: "列出;列入" }],
    "live": [{ pos: "v.", zh: "居住;生活;活着" }, { pos: "adj.", zh: "活的;现场的" }],
    "load": [{ pos: "n.", zh: "负载;负担;装载量" }, { pos: "v.", zh: "装载;加载" }],
    "loan": [{ pos: "n.", zh: "贷款;借款" }, { pos: "v.", zh: "借出" }],
    "lock": [{ pos: "n.", zh: "锁;水闸" }, { pos: "v.", zh: "锁上;固定" }],
    "long": [{ pos: "adj.", zh: "长的;长久的" }, { pos: "adv.", zh: "长久地" }, { pos: "v.", zh: "渴望" }],
    "look": [{ pos: "v.", zh: "看;看起来;寻找" }, { pos: "n.", zh: "看;神情;外观" }],
    "lose": [{ pos: "v.", zh: "失去;丢失;输掉;浪费" }],
    "loss": [{ pos: "n.", zh: "损失;丧失;亏损" }],
    "loud": [{ pos: "adj.", zh: "大声的;响亮的" }],
    "love": [{ pos: "v.", zh: "爱;热爱;喜欢" }, { pos: "n.", zh: "爱;爱情" }],
    "luck": [{ pos: "n.", zh: "运气;幸运" }],
    "mail": [{ pos: "n.", zh: "邮件;邮政" }, { pos: "v.", zh: "邮寄" }],
    "main": [{ pos: "adj.", zh: "主要的;最重要的" }, { pos: "n.", zh: "主要部分" }],
    "make": [{ pos: "v.", zh: "制造;做;使得;成为" }],
    "male": [{ pos: "adj.", zh: "男性的;雄性的" }, { pos: "n.", zh: "男性" }],
    "mark": [{ pos: "n.", zh: "标记;分数;痕迹" }, { pos: "v.", zh: "标记;打分;纪念" }],
    "mass": [{ pos: "n.", zh: "大量;质量;群众;弥撒" }],
    "mate": [{ pos: "n.", zh: "伙伴;同事;配偶" }],
    "meal": [{ pos: "n.", zh: "一餐;膳食" }],
    "mean": [{ pos: "v.", zh: "意思是;意味着;打算" }, { pos: "adj.", zh: "吝啬的;刻薄的;平均的" }],
    "meat": [{ pos: "n.", zh: "肉;肉类" }],
    "meet": [{ pos: "v.", zh: "遇见;会面;满足;迎接" }],
    "melt": [{ pos: "v.", zh: "融化;熔化;消失" }],
    "mind": [{ pos: "n.", zh: "头脑;思维;主意" }, { pos: "v.", zh: "介意;注意;照料" }],
    "mine": [{ pos: "pron.", zh: "我的" }, { pos: "n.", zh: "矿;矿山" }, { pos: "v.", zh: "开采" }],
    "miss": [{ pos: "v.", zh: "想念;错过;未击中" }, { pos: "n.", zh: "小姐" }],
    "mode": [{ pos: "n.", zh: "方式;模式;样式" }],
    "moon": [{ pos: "n.", zh: "月亮;月球" }],
    "more": [{ pos: "adj.", zh: "更多的" }, { pos: "adv.", zh: "更;更多" }, { pos: "pron.", zh: "更多" }],
    "most": [{ pos: "adj.", zh: "最多的;大多数的" }, { pos: "adv.", zh: "最;非常" }],
    "move": [{ pos: "v.", zh: "移动;搬家;感动;进展" }, { pos: "n.", zh: "移动;步骤" }],
    "much": [{ pos: "adj.", zh: "许多的;大量的" }, { pos: "adv.", zh: "非常;很" }],
    "must": [{ pos: "aux.", zh: "必须;一定;应当" }],
    "name": [{ pos: "n.", zh: "名字;名称;名声" }, { pos: "v.", zh: "命名;说出…的名字" }],
    "near": [{ pos: "prep.", zh: "在…附近;接近" }, { pos: "adj.", zh: "近的;亲近的" }, { pos: "adv.", zh: "近;接近" }],
    "neat": [{ pos: "adj.", zh: "整洁的;利落的;纯净的" }],
    "need": [{ pos: "v.", zh: "需要;必须" }, { pos: "n.", zh: "需要;需求" }],
    "news": [{ pos: "n.", zh: "新闻;消息" }],
    "next": [{ pos: "adj.", zh: "下一个的;紧接着的" }, { pos: "adv.", zh: "接下来;其次" }],
    "nice": [{ pos: "adj.", zh: "好的;友好的;令人愉快的" }],
    "nine": [{ pos: "num.", zh: "九;九个" }],
    "none": [{ pos: "pron.", zh: "没有人;没有任何东西" }],
    "noon": [{ pos: "n.", zh: "中午;正午" }],
    "nose": [{ pos: "n.", zh: "鼻子;嗅觉" }],
    "note": [{ pos: "n.", zh: "笔记;便条;音符;纸币" }, { pos: "v.", zh: "注意;记录" }],
    "obey": [{ pos: "v.", zh: "服从;遵守;听从" }],
    "once": [{ pos: "adv.", zh: "一次;曾经;一旦" }, { pos: "conj.", zh: "一旦;一…就" }],
    "only": [{ pos: "adv.", zh: "只;仅仅" }, { pos: "adj.", zh: "唯一的;仅有的" }],
    "open": [{ pos: "adj.", zh: "开着的;开放的;坦率的" }, { pos: "v.", zh: "打开;开始;开业" }],
    "oral": [{ pos: "adj.", zh: "口头的;口部的" }],
    "over": [{ pos: "prep.", zh: "在…上方;超过;关于" }, { pos: "adv.", zh: "结束;翻过来;再一次" }],
    "pack": [{ pos: "n.", zh: "包;背包;一包" }, { pos: "v.", zh: "打包;包装;挤满" }],
    "page": [{ pos: "n.", zh: "页;页面;侍从" }],
    "pain": [{ pos: "n.", zh: "疼痛;痛苦" }],
    "pair": [{ pos: "n.", zh: "一对;一双;一副" }, { pos: "v.", zh: "配对" }],
    "pale": [{ pos: "adj.", zh: "苍白的;浅色的" }],
    "park": [{ pos: "n.", zh: "公园;停车场" }, { pos: "v.", zh: "停放(车辆)" }],
    "part": [{ pos: "n.", zh: "部分;角色;零件" }, { pos: "v.", zh: "分开;分离" }],
    "pass": [{ pos: "v.", zh: "经过;通过;传递;度过" }, { pos: "n.", zh: "通行证;及格" }],
    "past": [{ pos: "n.", zh: "过去;昔日" }, { pos: "adj.", zh: "过去的" }, { pos: "prep.", zh: "经过;超过" }],
    "path": [{ pos: "n.", zh: "小路;道路;途径" }],
    "peak": [{ pos: "n.", zh: "山峰;顶点;高峰" }, { pos: "adj.", zh: "最高的;巅峰的" }],
    "pick": [{ pos: "v.", zh: "挑选;采摘;拾起" }, { pos: "n.", zh: "挑选;镐" }],
    "pile": [{ pos: "n.", zh: "堆;桩" }, { pos: "v.", zh: "堆放;堆积" }],
    "pink": [{ pos: "adj.", zh: "粉红色的" }, { pos: "n.", zh: "粉红色" }],
    "pipe": [{ pos: "n.", zh: "管子;管道;烟斗" }],
    "plan": [{ pos: "n.", zh: "计划;方案;平面图" }, { pos: "v.", zh: "计划;打算" }],
    "play": [{ pos: "v.", zh: "玩;演奏;扮演;进行(比赛)" }, { pos: "n.", zh: "戏剧;游戏;比赛" }],
    "plot": [{ pos: "n.", zh: "情节;阴谋;小块土地" }, { pos: "v.", zh: "密谋;绘制" }],
    "plus": [{ pos: "prep.", zh: "加;加上" }, { pos: "n.", zh: "加号;好处" }, { pos: "adj.", zh: "正的;有利的" }],
    "poem": [{ pos: "n.", zh: "诗;诗歌" }],
    "poet": [{ pos: "n.", zh: "诗人" }],
    "pole": [{ pos: "n.", zh: "杆;柱;极;极点" }],
    "pool": [{ pos: "n.", zh: "水池;游泳池;共用资源" }, { pos: "v.", zh: "合伙;共用" }],
    "poor": [{ pos: "adj.", zh: "贫穷的;可怜的;差的" }],
    "port": [{ pos: "n.", zh: "港口;口岸;(计算机)端口" }],
    "pose": [{ pos: "v.", zh: "摆姿势;造成;提出" }, { pos: "n.", zh: "姿势;姿态" }],
    "post": [{ pos: "n.", zh: "邮政;邮件;职位;柱子" }, { pos: "v.", zh: "邮寄;张贴;发布" }],
    "pour": [{ pos: "v.", zh: "倒;灌;倾泻;涌出" }],
    "pray": [{ pos: "v.", zh: "祈祷;恳求;请求" }],
    "pull": [{ pos: "v.", zh: "拉;拖;拔" }, { pos: "n.", zh: "拉力;吸引力" }],
    "pure": [{ pos: "adj.", zh: "纯的;纯净的;完全的" }],
    "push": [{ pos: "v.", zh: "推;推动;促使" }, { pos: "n.", zh: "推;推力" }],
    "quit": [{ pos: "v.", zh: "停止;放弃;辞职;离开" }],
    "race": [{ pos: "n.", zh: "比赛;竞赛;种族" }, { pos: "v.", zh: "参加比赛;赛跑" }],
    "rail": [{ pos: "n.", zh: "铁路;栏杆;轨道" }],
    "rain": [{ pos: "n.", zh: "雨;雨水" }, { pos: "v.", zh: "下雨" }],
    "rank": [{ pos: "n.", zh: "等级;军衔;排名" }, { pos: "v.", zh: "排列;评级" }],
    "rare": [{ pos: "adj.", zh: "稀有的;罕见的;半熟的" }],
    "rate": [{ pos: "n.", zh: "比率;速度;费用;等级" }, { pos: "v.", zh: "评估;估价" }],
    "read": [{ pos: "v.", zh: "阅读;朗读;读懂" }],
    "real": [{ pos: "adj.", zh: "真实的;真正的;实际的" }],
    "rent": [{ pos: "n.", zh: "租金;房租" }, { pos: "v.", zh: "租用;出租" }],
    "rest": [{ pos: "n.", zh: "休息;剩余部分" }, { pos: "v.", zh: "休息;放松;依靠" }],
    "rice": [{ pos: "n.", zh: "米饭;稻米" }],
    "rich": [{ pos: "adj.", zh: "富有的;丰富的;肥沃的" }],
    "ride": [{ pos: "v.", zh: "骑;乘;驾驶" }, { pos: "n.", zh: "乘坐;骑乘" }],
    "ring": [{ pos: "n.", zh: "戒指;环;铃声;电话" }, { pos: "v.", zh: "鸣响;打电话;环绕" }],
    "rise": [{ pos: "v.", zh: "升起;上升;增加;起床" }, { pos: "n.", zh: "上升;增长;兴起" }],
    "risk": [{ pos: "n.", zh: "风险;危险" }, { pos: "v.", zh: "冒险;使遭受危险" }],
    "road": [{ pos: "n.", zh: "路;道路;途径" }],
    "rock": [{ pos: "n.", zh: "岩石;石头;摇滚乐" }, { pos: "v.", zh: "摇摆;摇动" }],
    "role": [{ pos: "n.", zh: "角色;作用;职能" }],
    "roll": [{ pos: "v.", zh: "滚动;卷;翻滚" }, { pos: "n.", zh: "卷;名单;滚动" }],
    "roof": [{ pos: "n.", zh: "屋顶;顶部" }],
    "room": [{ pos: "n.", zh: "房间;空间;余地" }],
    "root": [{ pos: "n.", zh: "根;根源;根本" }, { pos: "v.", zh: "扎根;生根" }],
    "rope": [{ pos: "n.", zh: "绳;绳索" }],
    "rose": [{ pos: "n.", zh: "玫瑰;蔷薇;玫瑰花" }, { pos: "v.", zh: "rise 的过去式" }],
    "rude": [{ pos: "adj.", zh: "粗鲁的;无礼的;简陋的" }],
    "ruin": [{ pos: "v.", zh: "毁灭;毁坏;使破产" }, { pos: "n.", zh: "废墟;毁灭" }],
    "rule": [{ pos: "n.", zh: "规则;规定;统治;尺子" }, { pos: "v.", zh: "统治;支配;裁决" }],
    "rush": [{ pos: "v.", zh: "冲;奔;匆忙;催促" }, { pos: "n.", zh: "匆忙;冲刺;热潮" }],
    "safe": [{ pos: "adj.", zh: "安全的;平安的;稳妥的" }, { pos: "n.", zh: "保险箱" }],
    "sail": [{ pos: "n.", zh: "帆;航行" }, { pos: "v.", zh: "航行;启航;驾船" }],
    "sale": [{ pos: "n.", zh: "出售;销售;大减价" }],
    "salt": [{ pos: "n.", zh: "盐;食盐" }, { pos: "v.", zh: "加盐;腌" }],
    "same": [{ pos: "adj.", zh: "相同的;同样的" }, { pos: "pron.", zh: "同样的人或事物" }],
    "sand": [{ pos: "n.", zh: "沙;沙子;沙滩" }],
    "save": [{ pos: "v.", zh: "拯救;节省;储蓄;保存" }],
    "scan": [{ pos: "v.", zh: "扫描;细看;浏览" }, { pos: "n.", zh: "扫描" }],
    "seat": [{ pos: "n.", zh: "座位;席位" }, { pos: "v.", zh: "使就座;容纳" }],
    "seed": [{ pos: "n.", zh: "种子;籽;起源" }],
    "seek": [{ pos: "v.", zh: "寻找;寻求;试图" }],
    "seem": [{ pos: "v.", zh: "似乎;好像" }],
    "sell": [{ pos: "v.", zh: "卖;出售;推销" }],
    "send": [{ pos: "v.", zh: "发送;寄;派遣" }],
    "shop": [{ pos: "n.", zh: "商店;店铺;车间" }, { pos: "v.", zh: "购物" }],
    "show": [{ pos: "v.", zh: "显示;表明;展示;表演" }, { pos: "n.", zh: "表演;展览;节目" }],
    "shut": [{ pos: "v.", zh: "关闭;合上;停止" }],
    "sick": [{ pos: "adj.", zh: "生病的;恶心的;厌倦的" }],
    "side": [{ pos: "n.", zh: "边;侧面;方面;一方" }],
    "sign": [{ pos: "n.", zh: "标志;招牌;符号;手势" }, { pos: "v.", zh: "签名;示意;签署" }],
    "silk": [{ pos: "n.", zh: "丝绸;丝;丝织物" }],
    "sing": [{ pos: "v.", zh: "唱;唱歌;鸣叫" }],
    "sink": [{ pos: "v.", zh: "下沉;沉没;下降" }, { pos: "n.", zh: "水槽;洗涤槽" }],
    "site": [{ pos: "n.", zh: "地点;位置;网站;现场" }],
    "size": [{ pos: "n.", zh: "尺寸;大小;规模;号码" }],
    "skin": [{ pos: "n.", zh: "皮肤;皮;外皮" }],
    "slow": [{ pos: "adj.", zh: "慢的;缓慢的;迟钝的" }, { pos: "adv.", zh: "缓慢地" }, { pos: "v.", zh: "放慢" }],
    "snow": [{ pos: "n.", zh: "雪;下雪" }, { pos: "v.", zh: "下雪" }],
    "soap": [{ pos: "n.", zh: "肥皂" }],
    "soft": [{ pos: "adj.", zh: "软的;柔软的;温柔的;轻的" }],
    "soil": [{ pos: "n.", zh: "土壤;泥土;国土" }, { pos: "v.", zh: "弄脏" }],
    "some": [{ pos: "adj.", zh: "一些;若干;某个" }, { pos: "pron.", zh: "一些;某些" }],
    "song": [{ pos: "n.", zh: "歌曲;歌;歌唱" }],
    "soon": [{ pos: "adv.", zh: "很快;不久;马上" }],
    "sort": [{ pos: "n.", zh: "种类;类别;排序" }, { pos: "v.", zh: "分类;整理" }],
    "soul": [{ pos: "n.", zh: "灵魂;心灵;精神" }],
    "sour": [{ pos: "adj.", zh: "酸的;酸味的;发酵的" }],
    "spot": [{ pos: "n.", zh: "地点;斑点;污点;职位" }, { pos: "v.", zh: "发现;认出;弄脏" }],
    "star": [{ pos: "n.", zh: "星星;恒星;明星;星级" }, { pos: "v.", zh: "主演;标星" }],
    "stay": [{ pos: "v.", zh: "停留;保持;暂住" }, { pos: "n.", zh: "停留;逗留" }],
    "step": [{ pos: "n.", zh: "步骤;脚步;台阶;措施" }, { pos: "v.", zh: "踩;迈步;走" }],
    "stop": [{ pos: "v.", zh: "停止;阻止;停下;结束" }, { pos: "n.", zh: "停止;车站;逗留" }],
    "such": [{ pos: "adj.", zh: "这样的;如此的" }, { pos: "pron.", zh: "这样的人或事物" }],
    "suit": [{ pos: "n.", zh: "套装;西装;诉讼;花色" }, { pos: "v.", zh: "适合;合身;相配" }],
    "sure": [{ pos: "adj.", zh: "确信的;肯定的;可靠的" }, { pos: "adv.", zh: "当然;确实" }],
    "tail": [{ pos: "n.", zh: "尾巴;尾部;末端" }],
    "take": [{ pos: "v.", zh: "拿;带;花费;采取;乘坐;接受" }],
    "tale": [{ pos: "n.", zh: "故事;传说;叙述" }],
    "talk": [{ pos: "v.", zh: "说话;交谈;讨论" }, { pos: "n.", zh: "谈话;演讲;会谈" }],
    "tall": [{ pos: "adj.", zh: "高的;高大的" }],
    "tape": [{ pos: "n.", zh: "胶带;磁带;卷尺" }],
    "task": [{ pos: "n.", zh: "任务;工作;作业" }],
    "team": [{ pos: "n.", zh: "队;组;团队" }],
    "tear": [{ pos: "n.", zh: "眼泪;泪珠" }, { pos: "v.", zh: "撕;撕裂;扯破" }],
    "tell": [{ pos: "v.", zh: "告诉;讲述;辨别;吩咐" }],
    "tend": [{ pos: "v.", zh: "倾向;趋向;照料" }],
    "term": [{ pos: "n.", zh: "学期;术语;期限;条款" }],
    "test": [{ pos: "n.", zh: "测试;试验;测验" }, { pos: "v.", zh: "测试;检验" }],
    "text": [{ pos: "n.", zh: "文本;正文;短信" }],
    "than": [{ pos: "conj.", zh: "比;比起" }],
    "that": [{ pos: "pron.", zh: "那;那个" }, { pos: "conj.", zh: "引导从句" }],
    "them": [{ pos: "pron.", zh: "他们;她们;它们" }],
    "then": [{ pos: "adv.", zh: "然后;那时;那么" }],
    "they": [{ pos: "pron.", zh: "他们;她们;它们" }],
    "thin": [{ pos: "adj.", zh: "薄的;瘦的;稀疏的" }],
    "this": [{ pos: "pron.", zh: "这;这个" }, { pos: "adj.", zh: "这;本" }],
    "thus": [{ pos: "adv.", zh: "因此;这样;如此" }],
    "tide": [{ pos: "n.", zh: "潮汐;潮流;趋势" }],
    "till": [{ pos: "prep.", zh: "直到;到…为止" }, { pos: "conj.", zh: "直到…时" }],
    "time": [{ pos: "n.", zh: "时间;时刻;次数;时代" }, { pos: "v.", zh: "计时;安排时间" }],
    "tiny": [{ pos: "adj.", zh: "极小的;微小的" }],
    "tire": [{ pos: "v.", zh: "使疲劳;厌倦" }, { pos: "n.", zh: "轮胎" }],
    "tone": [{ pos: "n.", zh: "语气;音调;色调;风格" }],
    "tool": [{ pos: "n.", zh: "工具;用具;手段" }],
    "tour": [{ pos: "n.", zh: "旅行;旅游;巡回" }, { pos: "v.", zh: "旅游;巡回演出" }],
    "town": [{ pos: "n.", zh: "城镇;市镇;市中心" }],
    "trap": [{ pos: "n.", zh: "陷阱;圈套;困境" }, { pos: "v.", zh: "设陷阱;诱捕;困住" }],
    "tree": [{ pos: "n.", zh: "树;树木" }],
    "trip": [{ pos: "n.", zh: "旅行;旅程;绊倒" }, { pos: "v.", zh: "绊倒;轻快地走" }],
    "true": [{ pos: "adj.", zh: "真实的;正确的;忠诚的" }],
    "turn": [{ pos: "v.", zh: "转动;翻转;转变;轮流" }, { pos: "n.", zh: "转弯;轮流;转动" }],
    "type": [{ pos: "n.", zh: "类型;种类;字体" }, { pos: "v.", zh: "打字;输入" }],
    "ugly": [{ pos: "adj.", zh: "丑陋的;难看的;恶劣的" }],
    "unit": [{ pos: "n.", zh: "单元;单位;部件;一套" }],
    "upon": [{ pos: "prep.", zh: "在…之上;一…就;依靠" }],
    "used": [{ pos: "adj.", zh: "用过的;旧的;习惯于" }],
    "user": [{ pos: "n.", zh: "用户;使用者" }],
    "vast": [{ pos: "adj.", zh: "巨大的;广阔的;大量的" }],
    "vary": [{ pos: "v.", zh: "变化;改变;不同" }],
    "very": [{ pos: "adv.", zh: "非常;很;极其" }, { pos: "adj.", zh: "正是;恰好的" }],
    "view": [{ pos: "n.", zh: "视野;观点;景色;看法" }, { pos: "v.", zh: "查看;看待" }],
    "vote": [{ pos: "n.", zh: "投票;选票;表决" }, { pos: "v.", zh: "投票;选举" }],
    "wait": [{ pos: "v.", zh: "等待;等候;盼望" }, { pos: "n.", zh: "等待;等候" }],
    "wake": [{ pos: "v.", zh: "醒来;唤醒;觉醒" }],
    "walk": [{ pos: "v.", zh: "走;步行;散步" }, { pos: "n.", zh: "步行;散步;人行道" }],
    "wall": [{ pos: "n.", zh: "墙;墙壁;围墙" }],
    "want": [{ pos: "v.", zh: "想要;需要;缺少" }],
    "warm": [{ pos: "adj.", zh: "温暖的;热情的;暖色的" }, { pos: "v.", zh: "使暖和;变暖" }],
    "warn": [{ pos: "v.", zh: "警告;告诫;提醒" }],
    "wash": [{ pos: "v.", zh: "洗;洗涤;冲洗" }, { pos: "n.", zh: "洗涤;冲洗" }],
    "wave": [{ pos: "n.", zh: "波浪;波;挥手;浪潮" }, { pos: "v.", zh: "挥手;波动;飘动" }],
    "weak": [{ pos: "adj.", zh: "弱的;虚弱的;薄弱的;淡的" }],
    "wear": [{ pos: "v.", zh: "穿;戴;磨损;流露" }],
    "week": [{ pos: "n.", zh: "星期;周;一周" }],
    "well": [{ pos: "adv.", zh: "好;很好地;充分地" }, { pos: "adj.", zh: "健康的;良好的" }, { pos: "int.", zh: "嗯;好吧" }, { pos: "n.", zh: "井" }],
    "west": [{ pos: "n.", zh: "西方;西部" }, { pos: "adj.", zh: "西方的" }, { pos: "adv.", zh: "向西" }],
    "what": [{ pos: "pron.", zh: "什么;…的东西" }, { pos: "adj.", zh: "什么;多么" }],
    "when": [{ pos: "adv.", zh: "什么时候;何时" }, { pos: "conj.", zh: "当…时;既然" }],
    "wide": [{ pos: "adj.", zh: "宽的;广泛的;宽阔的" }, { pos: "adv.", zh: "广泛地;充分地" }],
    "wife": [{ pos: "n.", zh: "妻子;夫人" }],
    "wild": [{ pos: "adj.", zh: "野生的;狂野的;疯狂的" }],
    "will": [{ pos: "aux.", zh: "将要;会;愿意" }, { pos: "n.", zh: "意志;遗嘱;决心" }],
    "wind": [{ pos: "n.", zh: "风;气流;气息" }, { pos: "v.", zh: "缠绕;蜿蜒;上发条" }],
    "wine": [{ pos: "n.", zh: "葡萄酒;酒" }],
    "wing": [{ pos: "n.", zh: "翅膀;机翼;翼" }],
    "wipe": [{ pos: "v.", zh: "擦;抹;擦去" }],
    "wire": [{ pos: "n.", zh: "金属丝;电线;电报" }],
    "wise": [{ pos: "adj.", zh: "明智的;聪明的;博学的" }],
    "wish": [{ pos: "v.", zh: "希望;祝愿;想要" }, { pos: "n.", zh: "愿望;希望;祝愿" }],
    "with": [{ pos: "prep.", zh: "和…一起;具有;用;随着" }],
    "wolf": [{ pos: "n.", zh: "狼" }],
    "wood": [{ pos: "n.", zh: "木头;木材;树林" }],
    "word": [{ pos: "n.", zh: "单词;词;话语;诺言" }],
    "work": [{ pos: "v.", zh: "工作;劳动;起作用;运转" }, { pos: "n.", zh: "工作;作品;职业" }],
    "worm": [{ pos: "n.", zh: "虫;蠕虫;蚯蚓" }],
    "year": [{ pos: "n.", zh: "年;年份;年度" }],
    "zero": [{ pos: "num.", zh: "零;零点;零度" }],
    "zone": [{ pos: "n.", zh: "地带;区域;地区" }],
};
