/*
 * p了个s · 英语单词数独 词库 (src/game2/words.ts)
 * =============================================
 * 高考大纲词汇中的 4/5/6 字母常见词, 按长度分组(用于 word square 生成:
 * 每行一个单词, 每列同样拼成完整单词)。
 * 词表可按需扩充; 全部小写; 已按长度自动归组去重。
 */
export const WS_WORDS: Record<number, string[]> = {
    4: [
        "able", "acid", "area", "army", "baby", "back",
        "bake", "ball", "band", "bank", "bare", "base",
        "bath", "bear", "beat", "bell", "belt", "bend",
        "best", "bill", "bind", "bird", "bite", "blue",
        "boat", "body", "boil", "bold", "bomb", "bone",
        "book", "boot", "bore", "born", "boss", "both",
        "bowl", "burn", "bury", "busy", "cake", "call",
        "calm", "camp", "card", "care", "case", "cash",
        "cast", "cave", "cell", "chat", "city", "coal",
        "coat", "code", "coin", "cold", "come", "cook",
        "cool", "copy", "corn", "cost", "crop", "cure",
        "dark", "date", "dawn", "dead", "deal", "dear",
        "debt", "deep", "deny", "desk", "diet", "dirt",
        "dish", "door", "down", "draw", "drop", "drug",
        "drum", "duck", "dull", "dust", "duty", "each",
        "earn", "ease", "east", "easy", "edge", "else",
        "even", "ever", "exam", "exit", "face", "fact",
        "fade", "fail", "fair", "fall", "farm", "fast",
        "fate", "fear", "feed", "feel", "file", "fill",
        "film", "find", "fine", "fire", "firm", "fish",
        "five", "flag", "flat", "flow", "fold", "food",
        "fool", "foot", "form", "free", "from", "fuel",
        "full", "fund", "gain", "game", "gate", "gift",
        "give", "glad", "goal", "gold", "good", "grab",
        "gray", "grow", "hair", "half", "hall", "hand",
        "hang", "hard", "harm", "hate", "have", "head",
        "heal", "hear", "heat", "help", "hide", "high",
        "hill", "hire", "hold", "hole", "holy", "home",
        "hope", "host", "hour", "huge", "hunt", "hurt",
        "idea", "inch", "into", "iron", "item", "join",
        "joke", "jump", "just", "keen", "keep", "kick",
        "kill", "kind", "king", "kiss", "knee", "know",
        "lack", "lady", "lake", "land", "last", "late",
        "lazy", "lead", "leaf", "lean", "leap", "left",
        "lend", "less", "life", "lift", "like", "line",
        "link", "list", "live", "load", "loan", "lock",
        "long", "look", "lose", "loss", "loud", "love",
        "luck", "mail", "main", "make", "male", "mark",
        "mass", "mate", "meal", "mean", "meat", "meet",
        "melt", "mind", "mine", "miss", "mode", "moon",
        "more", "most", "move", "much", "must", "name",
        "near", "neat", "need", "news", "next", "nice",
        "nine", "none", "noon", "nose", "note", "obey",
        "once", "only", "open", "oral", "over", "pack",
        "page", "pain", "pair", "pale", "park", "part",
        "pass", "past", "path", "peak", "pick", "pile",
        "pink", "pipe", "plan", "play", "plot", "plus",
        "poem", "poet", "pole", "pool", "poor", "port",
        "pose", "post", "pour", "pray", "pull", "pure",
        "push", "quit", "race", "rail", "rain", "rank",
        "rare", "rate", "read", "real", "rent", "rest",
        "rice", "rich", "ride", "ring", "rise", "risk",
        "road", "rock", "role", "roll", "roof", "room",
        "root", "rope", "rose", "rude", "ruin", "rule",
        "rush", "safe", "sail", "sale", "salt", "same",
        "sand", "save", "scan", "seat", "seed", "seek",
        "seem", "sell", "send", "shop", "show", "shut",
        "sick", "side", "sign", "silk", "sing", "sink",
        "site", "size", "skin", "slow", "snow", "soap",
        "soft", "soil", "some", "song", "soon", "sort",
        "soul", "sour", "spot", "star", "stay", "step",
        "stop", "such", "suit", "sure", "tail", "take",
        "tale", "talk", "tall", "tape", "task", "team",
        "tear", "tell", "tend", "term", "test", "text",
        "than", "that", "them", "then", "they", "thin",
        "this", "thus", "tide", "till", "time", "tiny",
        "tire", "tone", "tool", "tour", "town", "trap",
        "tree", "trip", "true", "turn", "type", "ugly",
        "unit", "upon", "used", "user", "vary", "vast",
        "very", "view", "vote", "wait", "wake", "walk",
        "wall", "want", "warm", "warn", "wash", "wave",
        "weak", "wear", "week", "well", "west", "what",
        "when", "wide", "wife", "wild", "will", "wind",
        "wine", "wing", "wipe", "wire", "wise", "wish",
        "with", "wolf", "wood", "word", "work", "worm",
        "year", "zero", "zone",
    ],
    5: [
        "about", "above", "actor", "adapt", "admit", "adopt",
        "adult", "after", "again", "agent", "agree", "ahead",
        "allow", "alone", "along", "aloud", "alter", "among",
        "anger", "angle", "angry", "apart", "apple", "apply",
        "argue", "arise", "aside", "avoid", "awake", "award",
        "aware", "awful", "baker", "basic", "basis", "beach",
        "beard", "beast", "begin", "being", "below", "bench",
        "birth", "black", "blame", "blank", "blast", "bleed",
        "bless", "blind", "block", "blood", "board", "brave",
        "bread", "break", "brick", "bride", "brief", "bring",
        "broad", "brown", "brush", "build", "burst", "cabin",
        "candy", "carry", "catch", "cause", "cease", "chain",
        "chair", "chalk", "charm", "chart", "chase", "cheap",
        "cheat", "check", "cheek", "cheer", "chess", "chest",
        "chief", "child", "china", "claim", "clash", "class",
        "clean", "clear", "clerk", "climb", "clock", "close",
        "cloth", "cloud", "coach", "coast", "color", "cough",
        "count", "court", "cover", "crack", "craft", "crash",
        "crazy", "cream", "crime", "cross", "crowd", "crown",
        "cruel", "cubic", "curly", "curve", "cycle", "daily",
        "dance", "dealt", "death", "delay", "depth", "devil",
        "diary", "dirty", "doubt", "dozen", "draft", "drama",
        "dream", "dress", "drink", "drive", "drunk", "dying",
        "eager", "eagle", "early", "earth", "eight", "elder",
        "elect", "empty", "enemy", "enjoy", "enter", "equal",
        "error", "essay", "event", "every", "exact", "exist",
        "extra", "faint", "faith", "false", "fancy", "fatal",
        "fault", "favor", "fence", "fetch", "fever", "field",
        "fifth", "fifty", "fight", "final", "first", "fixed",
        "flash", "flesh", "float", "flood", "floor", "flour",
        "focus", "force", "forge", "forth", "forty", "forum",
        "found", "frame", "fresh", "front", "fruit", "funny",
        "ghost", "giant", "given", "glass", "globe", "glory",
        "goods", "goose", "grace", "grade", "grain", "grand",
        "grant", "grass", "grave", "great", "greed", "green",
        "greet", "guard", "guess", "guest", "guide", "guilt",
        "habit", "happy", "harsh", "haste", "heart", "heavy",
        "hello", "hobby", "honey", "honor", "horse", "hotel",
        "house", "human", "humor", "hurry", "ideal", "image",
        "imply", "index", "inner", "issue", "judge", "juice",
        "knife", "knock", "labor", "large", "laser", "later",
        "laugh", "layer", "learn", "least", "leave", "legal",
        "lemon", "level", "light", "limit", "liver", "lobby",
        "local", "logic", "loose", "lover", "lower", "loyal",
        "lucky", "lunch", "magic", "major", "march", "match",
        "mayor", "meant", "medal", "media", "mercy", "merit",
        "merry", "metal", "meter", "might", "minor", "minus",
        "mixed", "model", "money", "month", "moral", "motor",
        "mount", "mouse", "mouth", "movie", "music", "naked",
        "nasty", "naval", "nerve", "never", "newly", "night",
        "noble", "noise", "noisy", "north", "noted", "novel",
        "nurse", "occur", "ocean", "offer", "often", "onion",
        "opera", "order", "organ", "other", "ought", "outer",
        "owner", "paint", "panel", "panic", "paper", "party",
        "paste", "patch", "pause", "peace", "pearl", "penny",
        "phase", "phone", "photo", "piano", "piece", "pilot",
        "pitch", "place", "plain", "plane", "plant", "plate",
        "plead", "point", "polar", "pound", "power", "press",
        "price", "pride", "prime", "print", "prior", "prize",
        "proof", "proud", "prove", "pulse", "pupil", "purse",
        "queen", "quick", "quiet", "quite", "quote", "radio",
        "raise", "range", "rapid", "reach", "react", "ready",
        "refer", "reign", "relax", "reply", "right", "rigid",
        "rival", "river", "roast", "robot", "rough", "round",
        "route", "royal", "ruins", "ruler", "rural", "salad",
        "salty", "sauce", "scale", "scene", "scent", "scope",
        "score", "seize", "sense", "serve", "seven", "shade",
        "shake", "shall", "shame", "shape", "share", "sharp",
        "sheep", "sheet", "shelf", "shell", "shift", "shine",
        "shirt", "shock", "shoot", "shore", "short", "shout",
        "sight", "silly", "since", "sixty", "skill", "slave",
        "sleep", "slice", "slide", "smart", "smell", "smile",
        "smoke", "snake", "solar", "solid", "solve", "sorry",
        "sound", "south", "space", "spare", "speak", "speed",
        "spell", "spend", "spite", "split", "spoil", "sport",
        "staff", "stage", "stain", "stair", "stamp", "stand",
        "stare", "start", "state", "steal", "steam", "steel",
        "steep", "stick", "stiff", "still", "stock", "stone",
        "store", "storm", "story", "stove", "strap", "straw",
        "strip", "study", "stuff", "style", "sugar", "sunny",
        "super", "sweep", "sweet", "swing", "sword", "table",
        "taste", "teach", "teeth", "thank", "theme", "there",
        "these", "thick", "thief", "thing", "think", "third",
        "those", "three", "throw", "thumb", "tiger", "tight",
        "tired", "title", "today", "tooth", "topic", "total",
        "touch", "tough", "tower", "trace", "track", "trade",
        "trail", "train", "treat", "trend", "trial", "tribe",
        "trick", "troop", "truck", "truly", "trust", "truth",
        "twice", "uncle", "under", "union", "unite", "until",
        "upper", "upset", "urban", "usual", "utter", "valid",
        "value", "video", "virus", "visit", "vital", "vivid",
        "voice", "voter", "waste", "watch", "water", "weave",
        "weigh", "weird", "wheel", "where", "which", "while",
        "white", "whole", "whose", "width", "witch", "woman",
        "worse", "worst", "worth", "wound", "write", "wrong",
        "yield", "young", "youth",
    ],
    6: [
        "absorb", "accept", "access", "accuse", "across", "action",
        "active", "actual", "admire", "advice", "affair", "affect",
        "afford", "agency", "almost", "amount", "animal", "annual",
        "answer", "anyone", "anyway", "appear", "around", "arrive",
        "artist", "aspect", "assert", "assess", "assign", "assist",
        "assume", "attach", "attack", "attend", "author", "autumn",
        "avenue", "basket", "battle", "beauty", "become", "before",
        "behalf", "behave", "behind", "belief", "belong", "beside",
        "beyond", "bitter", "bloody", "bother", "bottle", "bottom",
        "branch", "breach", "breath", "bridge", "bright", "broken",
        "bronze", "bubble", "budget", "burden", "bureau", "butter",
        "button", "camera", "campus", "cancel", "cancer", "candle",
        "carbon", "career", "carpet", "castle", "casual", "cattle",
        "centre", "chance", "change", "charge", "choice", "choose",
        "church", "circle", "circus", "clever", "client", "clinic",
        "closed", "coffee", "collar", "colony", "column", "combat",
        "comedy", "commit", "common", "comply", "convey", "cooker",
        "copper", "corner", "cotton", "county", "couple", "course",
        "cousin", "create", "credit", "crisis", "critic", "custom",
        "damage", "danger", "deadly", "debate", "decade", "decide",
        "defeat", "defend", "define", "degree", "demand", "depart",
        "depend", "desert", "design", "desire", "detail", "detect",
        "device", "devote", "differ", "dinner", "direct", "divide",
        "doctor", "double", "dragon", "drawer", "driver", "during",
        "easily", "easter", "effect", "effort", "either", "emerge",
        "empire", "employ", "enable", "energy", "engage", "engine",
        "ensure", "entire", "escape", "estate", "exceed", "except",
        "excess", "excuse", "expand", "expect", "expert", "export",
        "expose", "extend", "extent", "factor", "fairly", "family",
        "famous", "farmer", "father", "fellow", "female", "figure",
        "filter", "finger", "finish", "flower", "follow", "forbid",
        "forest", "forget", "formal", "former", "foster", "fourth",
        "freeze", "friend", "fright", "frozen", "future", "gallon",
        "garden", "garlic", "gather", "gender", "genius", "gentle",
        "gently", "global", "golden", "govern", "growth", "guilty",
        "guitar", "hammer", "handle", "happen", "harbor", "hardly",
        "health", "heaven", "height", "hidden", "hollow", "honest",
        "honour", "horror", "hunger", "hunter", "ignore", "impact",
        "import", "income", "indeed", "inform", "injure", "insect",
        "inside", "insist", "intend", "invent", "invest", "invite",
        "island", "jacket", "jungle", "junior", "kidney", "killer",
        "labour", "ladder", "latest", "latter", "launch", "lawyer",
        "leader", "league", "length", "lesson", "letter", "likely",
        "liquid", "listen", "little", "lively", "living", "lonely",
        "loosen", "lovely", "luxury", "mainly", "manage", "manner",
        "market", "master", "matter", "medium", "member", "memory",
        "mental", "merely", "method", "middle", "mildly", "minute",
        "mirror", "modern", "modest", "moment", "monkey", "mostly",
        "mother", "motion", "murder", "muscle", "museum", "mutual",
        "myself", "narrow", "nation", "native", "nature", "nearby",
        "nearly", "needle", "nephew", "nobody", "normal", "notice",
        "notion", "number", "object", "obtain", "occupy", "offend",
        "office", "online", "oppose", "option", "orange", "origin",
        "output", "oxygen", "palace", "parent", "partly", "pencil",
        "people", "pepper", "period", "permit", "person", "phrase",
        "planet", "plenty", "pocket", "poetry", "poison", "police",
        "policy", "polish", "polite", "praise", "prayer", "prefer",
        "pretty", "prince", "prison", "profit", "proper", "public",
        "pursue", "puzzle", "racial", "random", "rarely", "rather",
        "rating", "reader", "really", "reason", "recall", "recent",
        "recipe", "record", "reduce", "reform", "refuse", "regard",
        "region", "regret", "reject", "relate", "relief", "remain",
        "remind", "remove", "repair", "repeat", "report", "rescue",
        "resist", "resort", "result", "retain", "retire", "return",
        "reveal", "review", "reward", "rhythm", "riddle", "robber",
        "rocket", "rubber", "sacred", "safety", "salary", "saving",
        "scheme", "school", "scream", "screen", "search", "season",
        "second", "secret", "secure", "select", "senior", "series",
        "settle", "severe", "shadow", "should", "signal", "silent",
        "silver", "simple", "simply", "single", "sister", "slight",
        "smooth", "soccer", "social", "softly", "solely", "speech",
        "sphere", "spirit", "spread", "spring", "square", "stable",
        "status", "steady", "sticky", "stress", "strict", "strike",
        "string", "stroke", "strong", "stupid", "submit", "subtle",
        "sudden", "suffer", "summer", "summit", "supply", "surely",
        "survey", "switch", "symbol", "system", "talent", "target",
        "temple", "tender", "terror", "theory", "though", "threat",
        "tissue", "tomato", "tongue", "toward", "tragic", "travel",
        "treaty", "tunnel", "twelve", "twenty", "unfair", "unique",
        "unless", "unlike", "update", "upward", "urgent", "useful",
        "valley", "victim", "viewer", "virtue", "vision", "volume",
        "wander", "weaken", "wealth", "weapon", "weight", "whilst",
        "widely", "winter", "wisdom", "within", "wonder", "wooden",
        "worker", "worthy", "writer", "yellow",
    ],
};

/* 困难难度词库: 较抽象/低频的 5 字母词(在全部 5 字母词之外精选) */
export const WS_WORDS_HARD: string[] = [
    "abyss", "acute", "adapt", "admit", "adopt", "align", "alter", "amend",
    "amuse", "annex", "apron", "arise", "array", "asset", "attic", "audit",
    "avert", "awake", "badge", "basin", "blade", "blend", "blink", "blunt",
    "boost", "breed", "bribe", "brink", "brisk", "brook", "brute", "bugle",
    "cabin", "canal", "cargo", "carve", "cedar", "chaos", "charm", "chart",
    "chasm", "choke", "chord", "chore", "civic", "clasp", "clerk", "cloak",
    "colon", "comet", "couch", "crate", "creed", "creek", "crisp", "dairy",
    "debut", "decay", "decoy", "defer", "dense", "depot", "derby", "ditch",
    "dodge", "drape", "dread", "drift", "drown", "dwell", "eager", "eerie",
    "elite", "embed", "enact", "entry", "equip", "erode", "erupt", "ethic",
    "evade", "evict", "excel", "exert", "exile", "expel", "fable", "feast",
    "fence", "ferry", "fetus", "fiber", "fiery", "flask", "flick", "flint",
    "flirt", "flock", "flour", "forge", "fraud", "frown", "fudge", "gauge",
    "glare", "gleam", "glide", "gloom", "grace", "graze", "grief", "grill",
    "groan", "groom", "harsh", "haste", "hatch", "haunt", "hinge", "hoist",
    "hound", "hover", "ivory", "jewel", "kneel", "lapse", "latch", "lemon",
    "lever", "lodge", "lofty", "lyric", "manor", "marsh", "mason", "melon",
    "merge", "merit", "motto", "mourn", "mural", "noble", "nomad", "notch",
    "nudge", "obese", "onset", "orbit", "ounce", "patio", "peach", "pedal",
    "perch", "peril", "petal", "petty", "plaid", "plank", "pluck", "plump",
    "porch", "prank", "preen", "prick", "pride", "prone", "prose", "prowl",
    "punch", "purge", "quake", "quell", "quill", "quilt", "quirk", "quota",
    "radar", "ranch", "razor", "rehab", "reign", "relic", "remit", "resin",
    "retch", "revel", "rhyme", "ridge", "rinse", "rogue", "rouge", "satin",
    "savor", "scald", "scant", "scarf", "scoff", "scold", "scoop", "scorn",
    "scour", "scout", "scowl", "scrap", "scuff", "seize", "sever", "shack",
    "shaft", "shard", "shave", "shawl", "shear", "shirk", "shrug", "shunt",
    "sinew", "siren", "skate", "skimp", "skirt", "skulk", "slack", "slake",
    "slant", "slash", "slate", "sleek", "sleet", "slope", "slump", "smack",
    "smear", "smirk", "smite", "snare", "snarl", "sneak", "sneer", "sniff",
    "snore", "snort", "soggy", "spade", "spark", "spasm", "spate", "spear",
    "speck", "spect", "spike", "spire", "spore", "sport", "spout", "sprig",
    "spurn", "squad", "squat", "stale", "stalk", "stall", "stark", "stash",
    "steep", "sting", "stink", "stint", "stoic", "stoop", "stout", "strap",
    "stray", "strew", "strut", "stump", "stunt", "suave", "sully", "surge",
    "surly", "swamp", "swarm", "swear", "sweat", "swell", "swift", "swine",
    "swirl", "swish", "swoop", "tacit", "taffy", "taint", "tango", "taunt",
    "tease", "tense", "tepid", "throb", "thump", "tinge", "torch", "tramp",
    "trash", "trill", "trout", "truce", "tweed", "twine", "twirl", "twist",
    "udder", "ulcer", "umbra", "upend", "usher", "utter", "valor", "vapor",
    "vault", "vaunt", "venom", "verge", "vigil", "villa", "viper", "vista",
    "vocal", "vogue", "vomit", "vouch", "wharf", "whiff", "whine", "whirl",
    "whisk", "wield", "wince", "wreak", "wreck", "wrest", "wring", "yearn",
];
